### ISSUE TITLE
sem.fit reports wrong effect sizes for missing paths when interaction already present in model

### ISSUE THREAD

**Issue by murphymv** [jslefche/piecewiseSEM#103]
Hi, 

I found this issue recently. Effect sizes for independence claims are reported wrongly if there is an interactive effect already in the model of the response variable being tested. What actually appears to get reported is the last variable in the model summary, which is always an interactive effect because of the way the variables are sorted in the output. Presumably the reported effect would be correct if the independence claim was testing a missing interactive effect that then happened to get reported last in the model summary for the claim.

Cheers,
Mark

Code to reproduce problem:

## Current package version (1.2.1)
install.packages("piecewiseSEM", dependencies = T)
library(piecewiseSEM)

## Create variables (x = exogenous, y = endogenous)
set.seed(1)
dat <- data.frame(
  x1 = rnorm(30),
  x2 = rnorm(30),
  y1 = rnorm(30),
  y2 = rnorm(30)
)

## Fit SEM
mods <- list(
  mod1 = lm(y1 ~ x1 + x2 + x1:x2, dat),
  mod2 = lm(y2 ~ x1 + x2 + x1:x2, dat) # no y1
)

## Check fit
sem.fit(mods, dat) # reported effect of missing y1 on y2: t = -0.2887, p = 0.7752

## Check model summary
summary(update(mods$mod2, . ~ . + y1)) # actual effect of y1: t = 0.262, p = 0.795 (reported effect is x1:x2)

**Comment by jslefche** [comment]
This is a big one, thanks for bringing it to my attention and I can't believe I missed this post!

The issue should be fixed in version 2.0:
```
devtools::install_github("jslefche/piecewiseSEM@2.0")
```

Marking as closed
