### ISSUE TITLE
Missing paths with factor predictors can give misleading results

### ISSUE THREAD

**Issue by fseaton** [jslefche/piecewiseSEM#107]
Hi, 
I’ve been fitting a model using a 5-level factor as a predictor. I noticed that when the missing path calculation includes a missing path from that factor to a response variable, the path coefficient for the missing path is the final line of the model summary which may not be representative of the total effect of the factor.
Some code to demonstrate what I mean is below. The y2 variable is significantly impacted overall by the factor x3, but the a-d comparison is non-significant. When the missing y2 ~ x3 path is evaluated in the second model list, it only takes the final a-d comparison coefficient giving a non-significant path which is not truly the case.

Thanks, 
Fiona

## example
library(piecewiseSEM)

_**# data generation**_
data <- data.frame(
  x1 = rnorm(100, 20, 2),
  x2 = rnorm(100, 10, 5),
  x3 = gl(4, k=1, length=100)
)

error <- rnorm(100,0,3)
data$y1 <- 0.5*data$x1 + data$x2 + error

levels(data$x3) <- c("-1","2","3","1")
data$x3n <- as.numeric(as.character(data$x3))
levels(data$x3) <- c("a","b","c","d")
summary(data)

error <- rnorm(100)
data$y2 <- 10*abs(data$x3n) + data$x2 + error
summary(data)

**_## show significant impact of x3 on y2_**
plot(y2 ~ x3, data)
summary(lm(y2 ~ x3, data))

**_## piecewise fitting_**
modlist1 <- list(
  lm(y1 ~ x1 + x2 + x3, data),
  lm(y2 ~ x2 + x3, data)
)
sem.fit(modlist1, data)
sem.coefs(modlist1)

**_## remove y1 ~ x3_**
modlist2 <- list(
  lm(y1 ~ x1 + x2 + x3, data),
  lm(y2 ~ x2, data)
)
sem.fit(modlist2, data)

**Comment by jslefche** [comment]
Yes this is a known issue with mutli-level factors. In fact there is no good way to conduct d-sep tests with a non-ordinal or non-binary factor. Contact me by email and perhaps we can work something out
