### ISSUE TITLE
Adjusted r-square for linear models?

### ISSUE THREAD

**Issue by Martin-Jung** [jslefche/piecewiseSEM#110]
Hi Jon,

I am currently playing around with the "piecewiseSEM" package (version 2.0) and trying to fit several simple linear models (`lm`) as piecewise structural equation models.

**With the r.square values:**  Looking into the methodology it seems as if non-adjusted r.square values are derived from the summary function.

~~~
> piecewiseSEM:::rsquared.lm
function (model) 
list(family = "gaussian", link = "identity", method = NA, R.squared = summary(model)$r.squared)
<environment: namespace:piecewiseSEM>
~~~
Is there a reason for using unadjusted r.square values?
Would there be an option to also ( or instead ) show the adjusted r.square ? So `adj.r.squared`

**Comment by jslefche** [comment]
Mostly for parity with other R2 values that do not report adjusted R2s...I could add it as a method though. stay tuned
