### ISSUE TITLE
Don't update lmerMod model with REML = FALSE if it is ran with REML = FALSE already

### ISSUE THREAD

**Issue by hikea** [jslefche/piecewiseSEM#111]
Hi, I've noticed that `sem.model.fits(modlist)` keeps refitting `lmerMod` models even if the models are ML (i.e. ran with `REML=F`). This is mainly a problem when fits take long time.

I looked at the code and I think something like `if(isREML(model_rt_log) == TRUE)` before line 140 and `else` after line 140 should work.

```R
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

packageVersion("piecewiseSEM")
[1] ‘1.2.1’
```

**Comment by jslefche** [comment]
Try the dev 2.0 version. It should not refit the models unless a null (intercept only) model needs to be fit to get the proper variance components

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

**Comment by jslefche** [comment]
The new function is `rsquared`

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

**Comment by hikea** [comment]
That helped. Thanks!
