### ISSUE TITLE
sem.fit with models including random term with several nested levels

### ISSUE THREAD

**Issue by mstrelin** [jslefche/piecewiseSEM#112]
Hi!

I am using the sem.fit function to do a path analysis. The models (glmmadmb and glmer ) included in the list I used as argument of sem.fit have a random term with two nested levels. 

M1<-glmmadmb(cbind(Nro_drupas, (ovulos - Nro_drupas)) ~ Tratamiento2 + Floracion + ovulos + orden +   (1|Planta**/Inflorescencia**), family="betabinom", link = "logit", data=datos)

M5<-glmer(ovulos ~ orden +  (1|Planta**/Inflorescencia**), family="poisson", data=datos)

MODELOS.Path1<-list(M1, M5)

Path.1<-sem.fit(MODELOS.Path1, datos, conditional = FALSE, corr.errors = NULL, add.vars = NULL, 
        grouping.vars = NULL, grouping.fun = mean, adjust.p = FALSE, basis.set = NULL, 
        pvalues.df = NULL, model.control = NULL, .progressBar = TRUE)

The sem.fit fuction runs when I pass this argument but the following error pops up: “Error: unparseable formula for grouping factor”. When I removed the “Inflorescencia” nested level I had no problems with running the sem.fit function. Hence, I infererd that there is a problem with using more than one nested level in the models included in sem.fit.

Is there a way of solving this problem? I would be realy thankful if you help me working this out.

Best,

Marina

**Comment by jslefche** [comment]
Sorry this has been hanging so long, still working on `glmmadmb` In the meantime try `MASS::glmmPQL`
