### ISSUE TITLE
including SAR models into piecewiseSEM

### ISSUE THREAD

**Issue by NivDeMalach** [jslefche/piecewiseSEM#113]
I would like to incorporate an object from the the class "errorsarlm" (from the package "spdep",the most common package for incorporating spatial autocorrelation). Is there a way to incorporate this type of class into piecewise SEM? If not, is there a "trick" for converting this class into a something that the package can accept?

Thanks,

Niv

**Comment by jslefche** [comment]
Check the dev version of the package (sent you an email)
