### ISSUE TITLE
Composites in piecewiseSEM

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#116]
So, you can implement composites in a piecewise-like approach, so long as you have only one response variable per composite. See this example using the Cardinale et al multivariate diversity productivity data:

```
library(lavaan)
cards<-read.csv("../data/cardinale.csv")

#make a new nonlinear column
cards$logN <- log(cards$N + 1e-6)
cards$logChl <- log(cards$Chl)
cards$logN2Cen <- (cards$logN-mean(cards$logN))^2

cardModel<-'
SA ~ logN + logN2Cen + SR
logChl ~ SA + logN
'

cardModelComposite <- '
N_effect <~ logN + logN2Cen
SA ~ 1*N_effect + SR
logChl ~ SA + logN
'
carCompositeFit <- sem(cardModelComposite, data=cards)
standardizedSolution(carCompositeFit)

#Three step process
#first, fit the observed variable model
n_comp_mod <- lm(SA ~ logN + logN2Cen + SR, data=cards)

#Use coefficients from the observed variable model to create a composite
cards$NComp <- with(cards, coef(n_comp_mod)[2]*logN + coef(n_comp_mod)[3]*logN2Cen)

#fit to get composite loadings
n_comp_loadings <- lm(NComp ~ logN + logN2Cen, data=cards)

#now, fit that final relationship
SA_comp <- lm(SA ~  NComp + SR, data=cards)

coef(SA_comp)
coef(n_comp_loadings)

coef(carCompositeFit)

```

**Comment by rbfontana** [comment]
Hello, 
I'm working with composite variables in piecewiseSEM, but I have one question. It's possible for standardized estimates coefficients to be greater than 1? I have two coefficients with values >1 and I don't know if it's a syntax error or a possible result.

**Comment by jslefche** [comment]
Yes, that is possible, especially when the SD of the response is small relative to the SD of the predictor

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
