### ISSUE TITLE
coefs fails with I() nonlinear terms

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#123]
```
adf <- data.frame(x = rnorm(100), y = rnorm(100))

mod <- psem(lm(y ~ x + I(x^2), data=adf), data=adf)

coefs(mod)
```

produces

`Error in `[.data.frame`(newdata., , x) : undefined columns selected
`

See also that basisSet handles `I(x^2)` weirdly as well.

**Comment by jebyrnes** [comment]
Perhaps add 

filterIStatements <- function(b) {

  b <- lapply(b, function(i) if(any(grepl("I\\(", i[1:2]))) NULL else i )

  b <- b[!sapply(b, is.null)]

  return(b)

}

**Comment by jslefche** [comment]
This should also fail with offsets

**Comment by jebyrnes** [comment]
OK, now it returns something - but not the squared term.
