### ISSUE TITLE
Summary needs more model specific information

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#134]
right now summary gives dsep tests and coefs. GIven the broad variety of model forms, and that people are highly likely to misuse SEM and fit models without evaluating them, we need to return, say, random effects structures and temporal correlaitons, etc. etc. in summary. Otherwise they will be ignored.

**Comment by jslefche** [comment]
Not sure about this since they can inspect the individual model structures. It does return RE in the call...
