### ISSUE TITLE
roxygenize documentation for 2.0

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#137]
The 2.0 .Rd files are currently not integrated with their component .R files for easy documentation generation. Will work on trying to fix this, as it makes automated builds and tests much easier.

**Comment by jebyrnes** [comment]
Created a new branch - https://github.com/jslefche/piecewiseSEM/tree/2.0-roxygen - please close this issue once it has been deemed a-ok and merged with 2.0. I'll continue working on this branch until told otherwise.

**Comment by jebyrnes** [comment]
Merged and it appears to work!

**Comment by jslefche** [comment]
Thanks, did you run a build check? My roxygen docs were throwing a bunch of errors…

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
Ah - I thought I was filling in something old. Can revisit and open this back up.
