### ISSUE TITLE
Intercept terms

### ISSUE THREAD

**Issue by cbrown5** [jslefche/piecewiseSEM#140]
Shipley 2009 seems to imply that when testing a path model you should centre the data and fix the intercept to zero: http://onlinelibrary.wiley.com/doi/10.1890/12-0976.1/full

How does sem.fit treat intercept when building the component models to calculate the C statistic?
The results of fixing vs not fixing the intercept when fitting linear models can be quite dramatically different.

**Comment by jslefche** [comment]
Huh can you give me the exact phrasing? I would not fix the intercept in any ecological models, unless there is an extremely good reason to do so

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by whalend** [comment]
@cbrown5, are you referring to this section late in the Introduction? 

> I fix the means of the variables to zero (i.e., I center each variable about its sample mean) because the DAG only describes the relationships between the variables. I must therefore estimate five slopes (path coefficients) and five variances for a total of K = 10 free parameters (Bollen 1989, Shipley 2000a). If I was interested in the intercepts of the variables then I would have to estimate five more free parameters.

**Comment by cbrown5** [comment]
Yep, that section thanks @whalend
