### ISSUE TITLE
distribution-specific variance of negative binomial (L342 in sem.model.fits.mod.R)

### ISSUE THREAD

**Issue by mkschneider** [jslefche/piecewiseSEM#143]
Nakagawa et al. 2017 suggest ln(1+1/lambda+1/theta) as distribution-specific variance for the negative binomial with log link (eq. 3.9). I didn't find this in sem.model.fits.mod.R. Guess it should be in L342, but maybe I am wrong.

**Comment by jslefche** [comment]
Working on this right now, check the 2.0 branch

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by mkschneider** [comment]
Oh sorry, didn't notice this. Thanks for putting to 2.0 that's great news.

**Comment by jslefche** [comment]
Check out the dev version and in particular `?rsquared` you may find what you are looking for there. Let me know if you encounter any issues! We are working to deal with OLRE right now so there will be more updates incoming soon

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by mkschneider** [comment]
That's great. Are there any plans to extend to certain models fitted by glmmadmb? The reason I am asking is that we are using beta regression for percentage data. The distribution-specific variance can be approximated using the delta method.

**Comment by jslefche** [comment]
Its on my to do list to support glmmadmb for the whole piecewise package but alas time is a premium –we are more focused on reinforcing the existing functionality and pushing the new version to CRAN atm

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________
