### ISSUE TITLE
Incorrect basis set for intercept only endogenous variable

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#146]
Using the keeley data set

```
keeley.sem4 <- psem(

  lm(hetero ~ distance, data = keeley),

  lm(rich ~ distance + hetero, data = keeley),
  
  abiotic ~ 1

)
```

produces the following basis set:
```

$`2`
[1] "abiotic"  "hetero"   "distance"

$`3`
[1] "abiotic"  "rich"     "distance" "hetero"  

```

Thus, missing abiotic distance. So, somehow it thinks that abiotic is exogenous, not endogenous. Will see if I can muck with that.

**Comment by jebyrnes** [comment]
Note, I can see cases where you would want it to be exogenous.....or others endogenous. Hrm. THis might prove a hair tricky?

**Comment by jslefche** [comment]
This is tough because the package is functioning exactly as intended… you could specify the `add.claims` argument to insert it

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
Ah! Missed the add.claims - which we'd need to add. I guess the question is, is this the correct default behavior?

**Comment by jslefche** [comment]
I think so…otherwise you open a whole can of worms with mediation

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
I think the issue is when you slice a variable out of the model. That's where I'm not so sure this is a good default behavior, but I can see the argument either way.

Can you provide the correct fishersC add.claims syntax for this example? I don't see a good code example about.

And how extensible is add.claims to other functions - summary, anova, etc? I can try and look at that this evening if you don't get a moment.

**Comment by jebyrnes** [comment]
(yes, I'm referring to ~ line 131 of the intro to piecewise fitting r code)

**Comment by jslefche** [comment]
Its already in `summary` …there might be documentation in the vignette. Or the Rd file for `summary`

Yes give it a go and let me know what you determine

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jslefche** [comment]
See #127
