### ISSUE TITLE
Autocorrelation and spaMM package 

### ISSUE THREAD

**Issue by ChangenetAlex** [jslefche/piecewiseSEM#147]
Is it planned yet to implement the calculations of R2m and R2c on the spaMM package objects ? I've tried to do the calculations manually following the method of Nakagawa et al. (2017) for spaMM objects but I am not completely sure if that makes sense for spatial GLMM.

**Comment by jslefche** [comment]
Not planned yet. It should be reasonable to extract the variance components…let me know if you need help

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________
