### ISSUE TITLE
pgls fails with data = 

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#151]
```
duffy.sem2 <- psem(
  
  pgls(Host.Range ~ Eusociality.index + Total.Mass.Female, duffy.merge),
  
  pgls(Rubble.Abundance ~ Eusociality.index + Host.Range, duffy.merge),
  
  data = duffy.merge
  
)
```

produces
``Error in 1:nrow(data) : argument of length 0

but if you remove `data =`, then it works.

Unless there's an additional covariance included, in which case it fails at summary.

This appears to be due to psem stripping out the data before sending the list to formatpsem which looks for the data set and rebuilds it if its not there.

**Comment by jslefche** [comment]
Fixed
