### ISSUE TITLE
2.0 no longer handles lmerTest objects

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#156]
Given its prevalence, should we fix this? It's odd to have it fail if someone forgets they're using it...

**Comment by jebyrnes** [comment]
(and by someone, I admit, I mean me)

**Comment by jslefche** [comment]
Are these not “merMod” objects? Ugh...

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
Nope - it’s a separate thing. lmerTest objects?

You get

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length




On Jun 15, 2018, at 3:56 PM, Jon Lefcheck <notifications@github.com<mailto:notifications@github.com>> wrote:

Are these not “merMod” objects? Ugh...

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net<http://www.jonlefcheck.net>

________________________________

**Comment by jebyrnes** [comment]
Nope - it’s a separate thing. lmerTest objects?

You get the following when you run `psem`

 `Error in '.rowNamesDF<-'(x, value = value) : invalid 'row.names' length`

**Comment by jslefche** [comment]
Might be easier to re-class as “merMod” and then use `pbkrtest` to get the P-values rather than lmerTest

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
Oh, that's not when I try and get p-values, it's when I try and just pull it in with psem. Likely an easy fix there in how lmerTest is futzing with things.

**Comment by jebyrnes** [comment]
Looks like between lmerTest versions, merModLmerTest became lmerModLmerTest. I fixed things so both old and new versions should work, although p-values are still from pbkrtest. Should think about letting folk still use lmerModLmerTest objects for that, but that's an issue for the future. Pull from devel branch when ready to fix on CRAN.

**Comment by carlos-arnillas** [comment]
Hello. I am having issues when I try to use an lmerTest object.
The problem appears at least in the "getCoefficients" function, as there is no category associated to an "lmerModLmerTest" class.

**Comment by jslefche** [comment]
I recommend using `lme4` and `piecewiseSEM` automatically computes P-values using the same approximation as implemented in the `pbkrtest` package. `lmerTest` was throwing some strange errors and at the time I released 2.0 had not been updated in some time

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by carlos-arnillas** [comment]
I see. Thanks. One quick suggestion: Could you add an informative error message? It took me a few hours to discover that the problem was a the unsupported method.

**Comment by jslefche** [comment]
Yes, will do…and will keep this issue open until I am able to fix it

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
