### ISSUE TITLE
psem doesn't pass data to formatpsem

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#157]
I know we did this in Wales as a temporary fix to a bug we didn't have find to squash. Should this be changed back now? Are things sufficiently fixed?

**Comment by jslefche** [comment]
I think its good either way now!

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jebyrnes** [comment]
Then we should change it back?

**Comment by jslefche** [comment]
Seems ok, I just fetched and no conflicts…

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by jslefche** [comment]
Its all good now... `formatpsem` grabs the data itself and doesn't inherit from `psem` which was throwing the errors
