### ISSUE TITLE
bug in testing recursive model

### ISSUE THREAD

**Issue by bobdouma** [jslefche/piecewiseSEM#161]
I found a bug in the piece of code that tests for non-recursive models (cyclic.r):
1) the warning should warn that the model is non-recursive
2) it produces a warning when it should not in my opinion. A minimal example is attached
[recursive_problem.txt](https://github.com/jslefche/piecewiseSEM/files/2253854/recursive_problem.txt)

**Comment by jebyrnes** [comment]
BTW: just confirmed this from another model - looking at it.

**Comment by jebyrnes** [comment]
OK, weirder, if you change the order of the equations in the above textile, the model is NOT flagged. Um....

**Comment by jebyrnes** [comment]
Maybe just borrow from graph? https://igraph.org/r/doc/is_dag.html

**Comment by bobdouma** [comment]
Good idea. The package ggm also has a function isAcyclic() that works fine. Before piecewiseSEM existed I used ggm to construct DAGs and test for cyclicity.

**Comment by jslefche** [comment]
Replaced with is_dag
