### ISSUE TITLE
standardized coefficients for log link

### ISSUE THREAD

**Issue by mkschneider** [jslefche/piecewiseSEM#163]
This is more a question than an issue: I have constructed a piecewise SEM in which one of the response variables is species richness. In mixed-effects regression we modeled richness using a negative binomial likelihood with log link. If I incorporate this regression into the SEM, no standardized coefficients are provided because it is not implemented in coefs(). What would be your advise to work around: (1) standardize all explanatory variables or (2) log-transform richness as in Lefcheck (2016) or (3) work on something similar to the binomial case developed by Grace et al. (2018)

**Comment by jslefche** [comment]
I would recommend hand-calculating the coefficients as in Grace et al. Drop me an email if you need help!

**Comment by mkschneider** [comment]
Many thanks for your direction. I'll study Grace et al. and am very happy to share what I'll come up.
