### ISSUE TITLE
S3 methods not exported for anova.psem with roxygen2

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#164]
WTF

**Comment by jslefche** [comment]
@jebyrnes any ideas? I have `@method anova psem` and `@export` in the documentation and for some reason `devtools::document()` is not writing them to the NAMESPACE

**Comment by jebyrnes** [comment]
Looks like the answer is here - https://github.com/r-lib/devtools/issues/1585 or here - https://stackoverflow.com/questions/27416846/exporting-an-s3-method-for-more-than-class-with-multiple-assignment

Does that help?

**Comment by jslefche** [comment]
i dont think so because i've only got one class "psem" which is exported. Its juist "anova.psem" that isnt showing up in the NAMESPACE--infuriating!

**Comment by jebyrnes** [comment]
Maybe one is somewhere else, lurking?

**Comment by jslefche** [comment]
Well car::Anova…but I removed it and still not writing to NAMESPACE. Just edited by hand for now. Had this problem before with summary and it just…went away

__________________________________
Jonathan S. Lefcheck, Ph.D.
Scientist/Coordinator, MarineGEO
Smithsonian Institution
647 Contees Wharf Rd
Edgewater, MD 21037-0028 USA

Phone: +1 (443) 482-2443
https://marinegeo.si.edu/
https://jonlefcheck.net/

**Comment by jdunic** [comment]
anova.psem was missing for me when I installed from github but when I ran load_all() on the dev code on my computer anova.psem showed up in the NAMESPACE and multigroup() now works.

**Comment by jslefche** [comment]
This bloody thing…let me know if you can figure this out. I’m drawing a blank

____________________________
Jonathan S. Lefcheck, Ph.D.
Coordinating Scientist, MarineGEO
Smithsonian Institution
https://marinegeo.si.edu/
Phone: +1 (443) 482-2443
https://jonlefcheck.net/

**Comment by jebyrnes** [comment]
OMG YOU GUYS.

1. It was in our build ignore.
2. It needed to have a different filename - anova.psem.R

Fixed.

**Comment by jslefche** [comment]
O.M.G. THANK YOU

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
