### ISSUE TITLE
Error with multiple binomial regression when including intercept

### ISSUE THREAD

**Issue by sweetmoniker** [jslefche/piecewiseSEM#166]
Sorry to be a bother. I can get results without issue from a multiple binomial regression without an intercept, but when I add "intercepts = TRUE" to the summary call, I get the following error:

Error in `[<-.data.frame`(`*tmp*`, which(ret$Predictor %in% numVars[-1]),  : 
  replacement has 3 rows, data has 2

y = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
x1 = c(1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0)
x2 = c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0)

psem.model = psem(glm(y ~ x1 + x2, family = binomial(), data = data.frame(y,x1,x2)))
summary(psem.model, intercepts = TRUE)

The issue only occurs with more than 1 independent variable. Any insight? Thanks.

**Comment by jslefche** [comment]
Hmm will have to look into this…might be an easy fix

____________________________
Jonathan S. Lefcheck, Ph.D.
Coordinating Scientist, MarineGEO
Smithsonian Institution
https://marinegeo.si.edu/
Phone: +1 (443) 482-2443
https://jonlefcheck.net/

**Comment by jslefche** [comment]
Yup easy fix...try now!

**Comment by sweetmoniker** [comment]
looks good! Thanks!
