### ISSUE TITLE
summary of psem with lmer returns empty coefficients dataframe while lme works

### ISSUE THREAD

**Issue by jbuerg** [jslefche/piecewiseSEM#169]
Hi!
I usually use lme4 for mixed effect models, so I wanted to use it for my SEM, too. Unfortunately, the summary and coef functions return empty objects. I use lme4 1.1-19, and lmerTest_3.0-1. I tried it with lmerTest loaded and without. nlme and lme return the coefs. (see below)
It's not the earlier issues with an error issued for KRmodcomp.lmerMod(model, reducMod) and also not the version problem of lme that occurred in Dec 2018. No errors or warnings happening, just the empty response.
Any ideas?

> 
```
BD.sem <- psem(
+   lme(FunComp_pl_num ~ SppN_real_lg2, random=~1|site, control=bb,data = Data),
+   lme(Plot_Biomass ~ SppN_real_lg2 + FunComp_pl_num, random=~1|site,control=bb, data = Data),
+   Data
+ )

coefs(BD.sem)
        Response      Predictor Estimate Std.Error  DF Crit.Value P.Value Std.Estimate    
1 FunComp_pl_num  SppN_real_lg2   1.4061    0.0484 927    29.0763       0       0.7052 ***
2   Plot_Biomass  SppN_real_lg2  53.9084    8.9424 926     6.0284       0       0.2052 ***
3   Plot_Biomass FunComp_pl_num  28.4951    4.3775 926     6.5094       0       0.2163 ***

> BD.sem <- psem(
+   lmer(FunComp_pl_num ~ SppN_real_lg2+(1|site), data = Data),
+   lmer(Plot_Biomass ~ SppN_real_lg2 + FunComp_pl_num +(1|site), data = Data),
+   Data
+ )
> coefs(BD.sem)
[1] Response     Predictor    Estimate     Std.Error    DF           Crit.Value   P.Value      Std.Estimate
[9]             
<0 Zeilen> (oder row.names mit Länge 0)

```>

**Comment by jslefche** [comment]
There is something with the matching on the rownames and the output from lme4 that may have stemmed from changes in lme4. Can you tell me which version you’re using? I will look into this soon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
I’ve pushed a few changes…please reinstall the development version from Github and let me know if this is fixed!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>



From: Lefcheck, Jonathan<mailto:LefcheckJ@si.edu>
Sent: Wednesday, January 23, 2019 2:10 PM
To: jslefche/piecewiseSEM<mailto:reply@reply.github.com>; jslefche/piecewiseSEM<mailto:piecewiseSEM@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Subject: RE: [jslefche/piecewiseSEM] summary of psem with lmer returns empty coefficients dataframe while lme works (#169)

There is something with the matching on the rownames and the output from lme4 that may have stemmed from changes in lme4. Can you tell me which version you’re using? I will look into this soon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
