### ISSUE TITLE
psem returns - for std coef in binomial glm

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#174]
```
data(shipley)

mod <- psem(
  glmer(Live ~ Growth + (1|site) + (1|tree),
        family=binomial(link = "logit"), data = shipley),
  data = shipley
)

coefs(mod)
```

produces
```

  Response Predictor Estimate Std.Error   DF Crit.Value P.Value Std.Estimate    
1     Live    Growth   0.3479    0.0584 1431     5.9556       0            - ***
```

Does the latent linear or OE approach not work for glmms

**Comment by jslefche** [comment]
It does just haven't implemented yet. Hope to be mid March

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

________________________________

**Comment by Fadrique** [comment]
Hello, any updates on getting std.Estimates when using glmer gamma("log")? I would also take hand-calculation suggestions if you have any. Thanks

**Comment by jslefche** [comment]
This is on the books for version 2.2 so closing
