### ISSUE TITLE
Error when calling summary(), dSep(), and fisherC() etc - differing numbers of rows

### ISSUE THREAD

**Issue by H-Waters** [jslefche/piecewiseSEM#177]
I'm getting this error when trying to run summary, dSep, and fisherC on a psem object:
```
Error in data.frame(Independ.Claim = paste(b[[i]][2], "~", rhs), ct[,  : 
  arguments imply differing number of rows: 1, 0
```
Here's a reproducible example with the shipley dataset. I thought that it might have something to do with categorical variables, so I've turned 'year' into a factor.

```
shipleymod <-  shipley[shipley$year %in% c(1970,1972,1974),] 
shipleymod$year <- as.factor(shipleymod$year)
shipleymod <- na.omit(shipleymod)
test <- psem(
lm(DD ~ lat + year, data = shipleymod),
lm(Date ~ DD, data = shipleymod),
data=shipleymod
)
summary(test)
dSep(test)
fisherC(test)
```

Thanks!

**Comment by jebyrnes** [comment]
Note `basisSet(test)` makes the categorical variable into one of the responses for a test of D separation. I **think** that's the problem.

**Comment by jebyrnes** [comment]
To solve this for now
```
dSep(test, direction = "Date -> year")
```

works?

Actually, huh, it then doesn't test the second claim.

**Comment by jebyrnes** [comment]
So for now, do it by hand?

**Comment by jebyrnes** [comment]
OK, fixed. If not, please re-open the issue.

**Comment by Melirax** [comment]
Hi, 

Now the error message for the 3 commands (summary, dsep and fisherC) is: 
```
in terms.formula(formula, data = data) : 
  l'argument 'data' est d'un mauvais type
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed
```

Thanks
