### ISSUE TITLE
multigroup() doesn't constrain

### ISSUE THREAD

**Issue by jbuerg** [jslefche/piecewiseSEM#178]
Although an interaction is non-significant in the summary, there are no constrained paths.
Jutila example below.
Updated the package today from github.

 > jutila <- psem(
+     lm(rich ~ elev + mass, data = meadows),
+     lm(mass ~ elev, data = meadows)
+ )
> 
> jutila.multigroup <- multigroup(jutila, group = "grazed")
> 
> jutila.multigroup

Structural Equation Model of jutila 

Groups = grazed [ 1, 0 ]

---

Global goodness-of-fit:

  Fisher's C = 0 with P-value = 1 and on 0 degrees of freedom

---

Model-wide Interactions:

  Response   Predictor       Sum Sq Df   F value      Pr(>F)   
      rich elev:grazed     12.74536  1 0.9290087 0.335789924   
      rich mass:grazed    126.28919  1 9.2052107 0.002594746 **
      mass elev:grazed 287418.50772  1 7.8200891 0.005452214 **

 No paths constrained to the global model (P > 0.05)

---

Group [1] coefficients: 

  Response Predictor Estimate Std.Error  DF Crit.Value P.Value Std.Estimate     
      rich      elev   0.0730    0.0102 162     7.1656  0.0000       0.4962  ***
      rich      mass  -0.0007    0.0017 162    -0.4198  0.6752      -0.0291     
      mass      elev  -1.2028    0.4728 163    -2.5438  0.0119      -0.1954    *
 
Group [0] coefficients: 

  Response Predictor Estimate Std.Error  DF Crit.Value P.Value Std.Estimate     
      rich      elev   0.0875    0.0110 186     7.9247       0       0.4710  ***
      rich      mass  -0.0072    0.0013 186    -5.4216       0      -0.3222  ***
      mass      elev  -3.2735    0.5571 187    -5.8764       0      -0.3948  ***
 
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05    c = constrained>

**Comment by jslefche** [comment]
This should be fixed now
