### ISSUE TITLE
summary gives differing number of rows error

### ISSUE THREAD

**Issue by crzirbel** [jslefche/piecewiseSEM#186]
I get the following error when running summary on a psem object.

`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 7, 6`

Reproducible example below:

`library(piecewiseSEM)`
`library(lme4)`

`#generated related variables`
`x<-rnorm(100)`
`y<-rnorm(100,exp(1 + 0.2*x))`
`z<-rnorm(100,exp(1.5 + 0.5*x))`

`#create data frame of random variables`
`data<-data.frame("forb.abun.logit"=x, "C4.grass.abun.logit"=y,
                 "C4.grass.seed.den"=rnorm(100),"nonsown.abun.logit"=z,
                 "last.burn"=sample(0:4,100,replace=T),"Age_2016"=sample(3:15,100, replace=T),
                 "forb.seed.den"=rnorm(100), "Water.Holding.Capacity"=rnorm(100))`

`#order data and add Site variable (random effect) to avoid singular fit`
`data<-data[order(data$forb.abun.logit),]              
data$Site<-rep(1:10,each=10)`

`#build models`        
`mod.forb.abun.sem<-lmer(forb.abun.logit~ C4.grass.abun.logit+ nonsown.abun.logit+ last.burn+Age_2016+Water.Holding.Capacity+ forb.seed.den+ (1|Site), data=data)`

`mod.C4.grass.abun.sem<-lmer(C4.grass.abun.logit~ C4.grass.seed.den+ Age_2016+last.burn+ Water.Holding.Capacity+(1|Site), data=data)`

`mod.nonsown.abun.sem<-lmer(nonsown.abun.logit~ C4.grass.abun.logit+ Age_2016+last.burn+ Water.Holding.Capacity+ (1|Site), data=data)`

`#create model list and run summary`
`mod.lst<-psem(mod.forb.abun.sem, mod.C4.grass.abun.sem, mod.nonsown.abun.sem)`
`summary(mod.lst)`

Any thoughts are greatly appreciated.

**Comment by jslefche** [comment]
Chad, try the development version:

devtools::install_github(“jslefche/piecewiseSEM@devel”)

and let me know if this persists


____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by crzirbel** [comment]
Hi Jon,

Installing the development version solves this issue.

Thanks!

**Comment by SusieJC** [comment]
Hi Jon,
I am recently experiencing the same issue as crzirbel (it's sudden - everything was working fine until ~ 2 weeks ago, I don't know what changed...must have updated something piecewiseSEM was relying on I gues..?). I have installed the development version, but this gives me a new issue when using the summary function: 

Error in GetAnova(model) : could not find function "GetAnova"

I'm a rookie here and have no idea what to do ... apologies if this is an easy & obvious fix,

Thanks!
Susie

**Comment by jslefche** [comment]
Should be fixed

**Comment by SusieJC** [comment]
Thank you-- yes it is! That's wonderful.

Many thanks again,

Susie

Dr Susan Cunningham

Lecturer
FitzPatrick Institute of African Ornithology
DST-NRF Centre of Excellence
University of Cape Town
Rondebosch 7701
South Africa

susie.j.c@gmail.com; sj.cunningham@uct.ac.za <susan.cunningham@uct.ac.za>

Phone +27-21-650 3306 <%2B27-21-6502966>
Mobile +27-76-894 6865 <%2B27-21-6502966>
Fax   +27-21-650 3295 <%2B27-21-6503295>
Skype  susan-cunningham

https://hbresearchproject.wixsite.com/hbresearchproject
<https://protect-za.mimecast.com/s/RSSxCAnX51i1YAJYU9MonK>


http://www.fitzpatrick.uct.ac.za/fitz/staff/academic/cunningham
<http://www.fitzpatrick.uct.ac.za/>

www.facebook.com/hotbirdsresearchproject

www.facebook.com/UCTstarlings

www.facebook.com/PFIAO

twitter @Fitztitute @kiwi_sjc
<https://twitter.com/Fitztitute>
