### ISSUE TITLE
Error when using summary function: "Calling var(x) on a factor x is defunct."

### ISSUE THREAD

**Issue by KwnLi** [jslefche/piecewiseSEM#187]
I am encountering an error when using `summary` on a `psem` object. I've recreated the error using some fake data that are based on my original dataset:

```
set.seed(42)

SEMtest<-data.frame(
  Treatment = sample(c("INSIDE","OUTSIDE"), 72, TRUE),
  PLOT.Size = sample(as.integer(c(5, 10, 20, 40)), 72, TRUE),
  PLOT.R = sample(0:6, 72, TRUE),
  Canopy = runif(72, 0, 1),
  Visits = rnbinom(72, mu = 10, size = 1),
  PlVol = rnorm(72, mean = 60, sd = 60),
  BloomTot = rnbinom(72, mu = 30, size = 2)
)

m1 <- glm(Canopy ~ PLOT.R + Treatment + PLOT.Size, data = SEMtest, family = Gamma)

m2 <- glm.nb(Visits ~ BloomTot, data = SEMtest)

m3 <- lm(PlVol ~ Canopy, data = SEMtest)

m4 <- glm.nb(BloomTot ~ Canopy + PlVol, data = SEMtest)

smod<-psem(m1, m2, m3, m4)
summary(smod)
```

Everything seems to work fine except when I try to run `summary()` on `smod`. Then I get the error:
```
Error in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm) : 
  Calling var(x) on a factor x is defunct.
  Use something like 'all(duplicated(x)[-1L])' to test for a constant vector.
```
I'm still learning piecewiseSEM, so sorry if this is a simple mistake on my part. I hope this is the right place to ask this. I couldn't find much about this error in Stackexchange.

Traceback:
```
13. var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm)
12. sd(newdata[, x], na.rm = TRUE)
11. FUN(X[[i]], ...)
10. lapply(X = X, FUN = FUN, ...)
9. sapply(f.notrans[!grepl(":", f.notrans)][-1], function(x) sd(newdata[, x], na.rm = TRUE))
8. FUN(X[[i]], ...)
7. lapply(1:length(modelList), function(i) { j <- modelList[[i]] f <- listFormula(list(j))[[1]] newdata <- data[, all.vars.merMod(f)] ...
6. do.call(rbind, lapply(1:length(modelList), function(i) { j <- modelList[[i]] f <- listFormula(list(j))[[1]] newdata <- data[, all.vars.merMod(f)] ...
5. stdCoefs(modelList, data, standardize, standardize.type, intercepts)
4. coefs(object, standardize, standardize.type, intercepts)
3. summary.psem(smod)
2. summary(smod)
1. summary(smod)
```

**Comment by jslefche** [comment]
Please try the development version:

devtools::install_github(“jslefche/piecewiseSEM@devel”)

It will give an error that you can ignore (that is a bug from use of glm.nb)

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by KwnLi** [comment]
Thanks! This seems to do the trick.

However, when I add an interaction between `Treatment` and `PLOT.Size` (my original intention was actually a three-way interaction between these two variables and `PLOT.R` before I began troubleshooting), I get another error: `Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument`

**Comment by jslefche** [comment]
Is one of your interaction terms a factor?


____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by KwnLi** [comment]
Yes, `Treatment` is a factor. Is this that the issue?

**Comment by jslefche** [comment]
Ah, yes, unfortunately. SEM was originally derived to use only continuous (normal) variables. We have only recently come up with strategies for incorporating both interactions \and\ categorical variables, but these are hardly formal.

The fact that you have a combination of the two (an interaction with a factor) is pushing the method beyond its current capabilities. Again, the strategies are generally to accommodate one or the other but often not both and at the level that is tempting (lots of interactions, factors, etc)

It may be best to transfer this conversation to email so we can perhaps find a strategy that works for your questions and data!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by srgriffin108** [comment]
I'm also having this issue with categorical variables (with lme models), though I don't have any interactions specified. Weirdly, the errors go away and the models run if I include an offset in the model, even though (I think) nlme does not support offsets. Is it just suppressing the error message?  Do I need to stay away from categorical variables altogether?

**Comment by jslefche** [comment]
Categorical variables are still in “beta”…SEM was only designed for continuous variables, and we have implemented some workarounds to accommodate a modest amount of categorical factors. Probably best to chat in private about your particular application!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
Should be fixed
