### ISSUE TITLE
constrained paths in `multigroup`

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#191]
...might still produce different unstandardized coefficients by group

**Comment by ingerdejonge** [comment]
I have been trying to use the multigroup function but it seems it is not functional anymore. Is this the reason and is it still under development?

**Comment by jslefche** [comment]
It should work in the development version: `devtools::install_github(“jslefche/piecewiseSEM@devel”)`

Let me know if not!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
I think i fixed this
