### ISSUE TITLE
NAs detected in the dataset - Trouble with Std.Estimate 

### ISSUE THREAD

**Issue by MarioSandoval-Mex** [jslefche/piecewiseSEM#193]
Dear Jon Lefcheck

I am writing to you because I have a problem with the piecewiseSEM package in R, and I would like to know if you can help me to solve this issue. I am trying to adjust two mixed-effects models one with the lme4 package and the other with nlme, both models use different databases:

  ```
 model.full <- psem( lme4::glmer(Number.of.insects~ V1 + V2+V3+ V4+ V5+ V2:V3 + V3:V1 + V1:V2 + (1|Patch), family = poisson("log"), data=datsc,control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=1000000)),na.action = na.omit),
   nlme::lme(Mean.ap ~ V1Temperatura +V2Int_luminica + V3Humedad+ V4hora_trans + V3:V2 + V3:V1 + V1:V2, random= ~ hr|Patch/ID, data=datsc2, control = lmeControl(opt='optim',msMaxIter = 5000, msVerbose = TRUE),method="REML",na.action = na.omit))
```
 
  However, I got the next warning:

**Warning message: NAs detected in the dataset. Consider removing all rows with NAs to prevent fitting to different subsets of data**  

 When I do summary to the psem object, another legend appears "Error in X[, rownames(i), drop = FALSE] : subscript out of bounds".  But, when I run "coefs(model.full)", I got incomplete Std.Estimates for the lme4::glmer model:

```
Std.Estimate    
1             - ***
2             -    
3             -   *
4             -    
5             - ***
6             -    
7             -    
8             -   *
9        0.1547    
10      -0.5483    
11      -0.1458  **
12       0.9749 ***
13       0.4041 ***
14       0.0365    
15       0.0933   
```

I have tried with different versions of the packages, re-installing all the packages, and with other laptops. But, I can't run the models and solve the problem. Currently I am working with the most updated version of the packages, for piecewiseSEM (2.1.0- development branch from github), lme4 (1.1-21) and nlme (3.1-140). I do not know what else to do, it is the same problem with GLM models.

Do you know what could be the problem? Can you help me with this?

Best regards

**Comment by remybeugnon** [comment]
Dear Jon, 

I am encountering the same issue, I am fitting my sem on several subsets of the dataset to avoid pseudo-replication. The SEM was fitting and working well, but since I updated R (4.1 - 4.3), I get this error. Any idea why?
