### ISSUE TITLE
Error in rsquared.glmerMod(i, method) : Unsupported link function!

### ISSUE THREAD

**Issue by bleavell** [jslefche/piecewiseSEM#194]
It looks like the "sqrt" link function in my poisson GLMM (glmer) is causing this error. It pops up when I run summary() for my pSEM model list. Do you know if there is currently a way around this, or if not, are there potential plans to support this link function in future versions?

Thanks!!

Brian

**Comment by jslefche** [comment]
Hi Brian, I added sqrt link for Poisson and negative binomial families—happy coding

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by bleavell** [comment]
Thank you, Jon!
