### ISSUE TITLE
coefs fails with single factor predictor

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#195]
```
library(lme4)

data <- data.frame(
  y2 = runif(100),
  y1 = runif(100),
  x = runif(100),
  x1 = sample(letters[1:5], 20, T),
  random = letters[1:4]
)

modelList <- psem(
  lmer(y1 ~ x1 + (1 | random), data),
  lmer(y2 ~ y1 + (1 | random), data),
  data
)

summary(modelList)
```

But is ok if you include continuous `x` as a covariate

**Comment by laureene** [comment]
Hello, 

I think I'm having this very issue and I was wondering if you have suggested workarounds, aside from converting the predictor to a continuous variable? I have non-normal data so I was hoping to use glmer with piecewiseSEM... 

Thank you for your time!

~L

**Comment by jslefche** [comment]
Seems to be fixed
