### ISSUE TITLE
Standardized coefficents for generalized linear (mixed) models

### ISSUE THREAD

**Issue by KwnLi** [jslefche/piecewiseSEM#198]
Are the `summary` and `coefs` functions supposed to return standardized coefficients for generalized linear (mixed) models? The documentation I've read seems to support this but I do not see it with my own data. 

I also don't see it in [this vignette](https://cran.r-project.org/web/packages/piecewiseSEM/vignettes/piecewiseSEM.html#glms-in-psem). In section 3.2 (screenshot below), the text implies that there should be a standardized coefficient, but the r output above does not show it. Or am I missing something?

![image](https://user-images.githubusercontent.com/51508158/71179156-e52f0680-226f-11ea-8dd5-199599f562af.png)

**Comment by bleavell** [comment]
According to the coefs.R code, binomial GL(M)Ms should produce Std.Estimates. (Maybe the entry in the vignette is old?) They work through examples in Grace et al. (2018) Ecosphere:

https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.2283 

I am also wondering about standardized estimates for GL(M)Ms. In particular, I would like to find the standardized betas for Poisson GLMMs with square root link functions. However, I'm finding this to be a difficult task to hand-calculate! Is there a chance that this might be added to piecewiseSEM in the near-future? Or do you know of a resource I can use to derive standardized betas for such models without having to transform my data?

Thanks, Jon!!

**Comment by jslefche** [comment]
Right now the application is only for GLM with a binomial distribution (as formalized in the paper). We have worked up (in theory) a way to extrapolate to multi-level models and other distributions. Version 2.2 of the package will include those generalizations, but it may take me into the spring to get that implemented---thanks for your patience!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by bleavell** [comment]
That sounds great, can't wait! Thanks for letting me know.

**Comment by KwnLi** [comment]
Thanks everyone for the information and update. Sorry about the delay in
reply.

Thanks Jon for working on this and providing updates. Happy New Year!

**Comment by emjbarrie** [comment]
Hello,

I'm also interested in this issue. I know it was posted a while ago so I was wondering if it might still be planned to be available in a version this spring? Thank you!

**Comment by jslefche** [comment]
Hi, I plan to get to this later this month but won’t make any promises ☹ I understand it is a huge feature request so am dedicated to providing a solution as soon as time allows!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by sashavas3** [comment]
Hello,

I was wondering if the recently implemented https://rdrr.io/cran/piecewiseSEM/man/GetSDy.html tackles this issue? I have tried to install it, but keep getting the message that it is not available for my version of R (I've tried 4.0.0 to 4.0.5 so far). Am I missing something?

Thank you

**Comment by jslefche** [comment]
The development version of the package should have additional standardized coefficients for GLMM. Try to install that using devtools:

***@***.***”)`

And see if that works!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by sashavas3** [comment]
Thanks! I've been trying to install it using devtools but I keep getting these errors on each attempt:

Installing package into ‘C:/Users/Sasha/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'piecewiseSEM' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'ellipsis' 0.3.1 is being loaded, but >= 0.3.2 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'piecewiseSEM'
* removing 'C:/Users/Sasha/Documents/R/win-library/4.0/piecewiseSEM'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Sasha/AppData/Local/Temp/RtmpYbZn0C/file2b5412a952fe/piecewiseSEM_2.1.2.tar.gz’ had non-zero exit status

This happens after getting a recommendation to update some packages:

Downloading GitHub repo jslefche/piecewiseSEM@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?
1: All                               
2: CRAN packages only                
3: None                              
4: rlang    (0.4.10 -> 0.4.11) [CRAN]
5: ellipsis (0.3.1  -> 0.3.2 ) [CRAN]
6: curl     (4.3    -> 4.3.2 ) [CRAN]

Do you have any suggestions on how to solve this issue?

Thank you!

**Comment by jslefche** [comment]
Hmm, try installing the packages individually using `install.packages`. If that does not work, see that there is not a folder called 00LOCK in your “packages” directory. If so, delete that. Also please try restarting R and ensuring that you have the latest version of that (and Rstudio) installed

HTH,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by sashavas3** [comment]
The individual installation of the packages and updating R and Rstudio to the latest versions seems to have done the trick.

Thanks very much!
