### ISSUE TITLE
Getting exact p-values

### ISSUE THREAD

**Issue by sdoms** [jslefche/piecewiseSEM#199]
Hi, 

Is it possible to get the exact p-values instead of the rounded p-values?

**Comment by jslefche** [comment]
Yes you can extract use the `dSep` function on the psem object!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by sdoms** [comment]
Sorry, I should have specified that I meant the p-values that are reported for each of the coefficients.  _coefs(model)$P.Value_ also gives the rounded p-values.

**Comment by jslefche** [comment]
Whoops, use the function `stdCoefs` instead…that will get you full P-values!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by sdoms** [comment]
Awesome thanks!
