### ISSUE TITLE
Post-hoc results not displayed?

### ISSUE THREAD

**Issue by ghost** [jslefche/piecewiseSEM#200]
Hi, 
I am running several models including a categorical variable with 3 levels. When I run coefs to get the post-hoc tests on the marginal means I can see the letters at the end of the line. I feal dumb but I can't even see them in  the SEM book ! Am I missing something? Here is the table I get:

   Response  Predictor Estimate Std.Error DF Crit.Value P.Value Std.Estimate    
1     mean_PD mean_alpha   1.4999    0.0748 67    20.0579  0.0000       0.9239 ***
2     mean_FD mean_alpha    0.093    0.0173 65     5.3772  0.0000       0.7101 ***
3     mean_FD       Etat        -         -  2     5.3022  0.0706            -    
4     mean_FD  Etat = HD    7.548    0.4961  2    15.2133  0.0043            -  **
5     mean_FD  Etat = MD   7.7757    0.4884  2    15.9207  0.0039            -  **
6     mean_FD  Etat = RF   8.4948    0.4568  2    18.5964  0.0029            -  **
7  mean_alpha       Etat        -         -  2    16.0739  0.0003            - ***
8  mean_alpha  Etat = HD   27.556    7.8998  2     3.4882  0.0733            -    
9  mean_alpha  Etat = MD  38.8228    7.8628  2     4.9375  0.0387            -   *
10 mean_alpha  Etat = RF  31.4914    7.8215  2     4.0263  0.0565            -    

Thanks

**Comment by jslefche** [comment]
Hi, Are you saying that you get different looking output between the example and your code, or that the example discusses the letters but they don’t appear in any output? If the latter, I believed I removed those as they were making the tables cluttered. HTH, Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
