### ISSUE TITLE
Error using summary in a psem object

### ISSUE THREAD

**Issue by aberenicega** [jslefche/piecewiseSEM#201]
Hi!

I'm running a psem where each path is an errorsarlm model. I don't know what is happening. The psem function ended without errors or warnings, but when I want to do the psem summary or use the coefs function only got this error:

Error in terms.default (i): no terms component nor attribute

I've been looking for a solution unsuccessfully. I've verified several times the formulas in each path and guess that not have any error. Because I also ran the psem with a lm model in each path and same data. Then, when I do the summary of psem with lm models I can see the results without errors.
I'm thinking the problem is to related to the errorsarlm inside the psem, because I can run each model path outside of the psem without problems.

Thanks!!! 
Berenice

**Comment by jslefche** [comment]
Yes that seems likely, it has been a long time since someone ran errorsarlm models, and its possible that package has made changes to make it incompatible with the current version of psem. Can you provide a reproducible bit of code and I can look into it?

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net

**Comment by aberenicega** [comment]
Thanks for your answer!
It will not be necessary to send you my code, I could run it this morning.

Thinking about incompatibility, I changed my R v3.6.1 with the current version of piecewiseSEM v2.1.0 and SpatialReg to R v3.5.2 where I had installed piecewiseSEM 2.0.2 and SpatialReg v1.1-3.

I ran the same code with the modelsarlm error and the same data in piecewiseSEM 2.0.2, and I did not receive any error or warning with the psem, coefs or summary functions.
The latest version of piecewiseSEM v2.1.0 was the problem.

Regards!
Bere

**Comment by jslefche** [comment]
Ah thanks, clearly something is broken there. I am preparing to go on extended travel so it may take me amonth or two to check this out. In the interim, please use 2.0.2 as not much will have changed that impacts this instance

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
