### ISSUE TITLE
Problems with lagsarlm

### ISSUE THREAD

**Issue by orrortega** [jslefche/piecewiseSEM#203]
Hi Jon,

I am trying to re-run a script that it worked before (Feb 2020) and now I am getting the following error:

model2_2spacelag<-psem(
  lagsarlm(perc_ fores~paved_ dist + unpav_ dist, data=yag, listw=spatial_ weights, tol.solve = 1e-11),
  lagsarlm(perc_ open~paved_ dist + unpav_ dist, data=yag, listw=spatial_ weights, tol.solve = 1e-11),
  lagsarlm(perc_ farmi~paved_ dist + unpav_ dist, data=yag, listw=spatial_ weights, tol.solve = 1e-11),
  lagsarlm(urban_ dist~paved_ dist + unpav_ dist, data=yag, listw=spatial_ weights, tol.solve = 1e-11),
  lagsarlm(freq_ rel~perc_ fores+perc_open+perc_ farmi+urban_ dist + unpav_ dist+paved_ dist, yag,
                    listw=spatial_ weights, tol.solve = 1e-11)
)

Error in max(sapply(nm[dfdetect], nrow)) : 
  invalid 'type' (list) of argument

I don't know if there is something that I am doing wrong or something that has change in the package.

Thanks in advance,

Oscar

**Comment by jslefche** [comment]
Hi Oscar, yes it is likely something in the package. I have not focused on sarlm integration lately. I’m not sure if I will be able to fix the below errors quickly, so you might revert to using an earlier version from Github until then—sorry! J

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
