### ISSUE TITLE
Problems with pgls implementation

### ISSUE THREAD

**Issue by msundara1001** [jslefche/piecewiseSEM#204]
Hello, 

I as able to piecewiseSEM to run regular lm regression models, however, I get an error when I switch to using pgls. I was wondering if the pgls implementation is still available in psem?

Here is my R code and error:
data.merge=comparative.data(phy,data,names.col="taxon")
sem1 <- psem(
  pgls(log(seed_volume) ~ clim1+clim2+clim3+clim4+clim5+clim6+biotic_specialized, data.merge)
)

The data.merge works without error, but the psem function produces this error:
Error in as.data.frame.default(data) : 
  cannot coerce class ‘"comparative.data"’ to a data.frame

Also the pgls code alone works, but does not work in function 'psem'.

Thanks for your assistance and the detailed vignettes for this R package,
Mekala

**Comment by jslefche** [comment]
Hi Mekela ,

Hmm, this must be an issue with some of the new data merging functions and the comparative data frame. It may take me some time to get to this. In the interim, please feel free to use an older version of the package. It should be fine for your purposes

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
