### ISSUE TITLE
wrong R2=1.00 obtained when using a proportion as response variable

### ISSUE THREAD

**Issue by filipapalmeirim** [jslefche/piecewiseSEM#205]
Hi,

I am modelling a tetra-trophic foodweb, so I have 4 GLMs. In one of those GLMs, I am using as response variable that is a proportion (0 - 100%). For this model, I obtain a R2 = 1.00, even if I change the exogenous or other endogenous variables (that are not the response variable). I am using a Gaussian distribution as I could not find other that better fit the data that is currently available in piecewiseSEM. I know the R2 = 1.00 I am getting is not the true value, I can run the GLM out of the piecewiseSEM framework and I get a R2 = 0.37, which is the kind of value I was expecting to obtain (even using the gaussian the distribution also here). Do you have any clue why this is happening and how could I solve it?

I was expecting to ask about this in the 5 days course in Glasgow but that have to be postponed due to the current situation... 

Thank you in advance!

Best wishes

**Comment by jslefche** [comment]
Hi please send me an email with an example of the code& data (if you are able)—happy to look into this for you

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by filipapalmeirim** [comment]
Thank you very much. What would be the email that I should send it for, please?

**Comment by jslefche** [comment]
Please check the maintainer email in the package : `help(“piecewiseSEM”)` ??

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
