### ISSUE TITLE
an error of piecewiseSEM running

### ISSUE THREAD

**Issue by hall-wang** [jslefche/piecewiseSEM#206]
Dear jslefche,
Something goes wrong when I run original code and data in your paper supporting file, PIECEWISESEM: Piecewise structural equation modelling in R for ecology, evolution, and systematics, Methods in Ecology and Evolution 2015.
After install and library the piecewiseSEM (version 2.1.0), an error show that function "sem.fit" could not be found , as well as function sem.model.fits and and sem.coefs.
I don't know how to fix it and I look forward to your reply.
Thanks for your attention.

**Comment by jslefche** [comment]
Hello, Those earlier functions were deprecated. You should receive a warning to use `psem` and `summary` instead. Please review `vignette(“piecewiseSEM”)` to become familiar with the new syntax—and do email if you run into any issues!

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by PierreSovegnon** [comment]
I evryone
Hi everyone
I'm looking to do SEM but I'm having trouble. 
Here is my error message
 
model1 <- psem(
+  lm(Prop.bottom ~ Food+Bednet, KISUMU),
+   lm(Mortality.24hrs ~ Prop.bottom*Food*Bednet,KISUMU))
> summary(model1, conserve = T, .progressBar = T)
Error in names(B) <- numVars : 
  'names' attribute [6] must be the same length as the vector [3]


Can you help me?
