### ISSUE TITLE
multigroup error message with glmmPQL

### ISSUE THREAD

**Issue by t-siqueira** [jslefche/piecewiseSEM#211]
library(piecewiseSEM)

##An example that will give an error message:

df = data.frame(
  y2 = rnorm(120, mean = 30, sd = 2),
  y1 = rnorm(120, mean = 15, sd = 2),
  x1 = rnorm(120, mean = 5, sd = 2),
  gr = rep(c("A", "B"), 60),
  reg = rep(c("a", "b", "c"), 40)
)

sem_mm = psem(
  glmmPQL(y2 ~ y1 + x1, random = ~ 1|reg,
          family = Gamma(link = "log"), data = df),
  glmmPQL(y1 ~ x1, random = ~ 1|reg,
          family = Gamma(link = "log"), data = df))

multigroup(sem_mm, group = "gr")

##Error in `[.data.frame`(data, , group) : undefined columns selected

##Not sure why sem_mm$data does not include the variable "gr".

##If I try a different sem everything works fine.

sem_mm2 = psem(
  glmmPQL(y2 ~ y1 + x1, random = ~ 1|reg,
          family = Gamma(link = "log"), data = df),
  lme(y1 ~ x1, random = ~ 1|reg, data = df))

multigroup(sem_mm2, group = "gr")

##sem_mm2$data includes the variable "gr"

## One solution as suggested by Jon - just provide the data argument to psem:

df = data.frame(
  y2 = rnorm(120, mean = 30, sd = 2),
  y1 = rnorm(120, mean = 15, sd = 2),
  x1 = rnorm(120, mean = 5, sd = 2),
  gr = rep(c("A", "B"), 60),
  reg = rep(c("a", "b", "c"), 40),
  data = df
)

**Comment by jslefche** [comment]
should be fixed for tbl now
