### ISSUE TITLE
reference to deprecated function emmeans::CLD

### ISSUE THREAD

**Issue by rvlenth** [jslefche/piecewiseSEM#212]
For some time, `emmeans::CLD()` has had a deprecated status. With the latest version, I attempted to remove `CLD` completely but I observed a checking error against your package:

```r
Package: piecewiseSEM
Check: Rd cross-references
New result: WARNING
  Missing link or links in documentation object 'coefs.Rd':
    ‘CLD’
```
I relented and put `CLD` back in for now. But I will take it out on the next update, which could be as early as Sept 12, 2020. In the meantime,

  * Change the link in `coefs.Rd` to `\link[emmeans:CLD.emmGrid]{cld.emmGrid}`
  * Encourage your users to use `multcomp::cld()` -- NOT `emmeans::CLD()`

Thanks -- Russ

**Comment by rvlenth** [comment]
Update on this issue: I alterted you about this in August. I suggested that it needed to be fixed by September. Now it is December and **emmeans** version 1.5.3 has been submitted to CRAN; and with this version, `CLD()` is gone completely. This causes and error in your package.

**Comment by rvlenth** [comment]
There is a typo in my earlier suggestion for the link. It should be `\link[emmeans::cld.emmGrid]{cld.emmGrid}`

**Comment by jslefche** [comment]
Sorry for the delay, thanks for the continued reminders. Updated and merged with master branch, pushing to CRAN now
