### ISSUE TITLE
AICc issues at very small sample sizes and over-paramaterized models

### ISSUE THREAD

**Issue by ctlamb** [jslefche/piecewiseSEM#213]
If one has too few data and/or the model is over parametrized the AICc calculation can be problematic (see below). The issue is that this error allows models with few data, but MORE parameters to outcompete simpler models because n-K-1 becomes negative and starts making the AIC value much lower. I was wondering if it would help if the package had a warning in this case.

An example:

```
dat <- data.frame(x1 = runif(9), y1 = runif(9), y2 = runif(9), y3 = runif(9))

model <- psem(lm(y1 ~ x1 + y2, dat), lm(y2 ~ x1, dat))
model <- update(model,y3 ~ 1)

model2 <- psem(lm(y1 ~ x1, dat), lm(y2 ~ x1, dat), lm(y3 ~ y1, dat))

AIC(model, aicc=TRUE)
>163.152

AIC(model2, aicc=TRUE)
>-224.118

##Find issue
C <- summary(model2)$Cstat$Fisher.C
K <- summary(model2)$IC$K
n <- summary(model2)$IC$n

(n-K-1) ##becomes negative
> -1
```

**Comment by jslefche** [comment]
This is an interesting point but a property of the metric, not the package, so going to close for now
