### ISSUE TITLE
summary fails for piecewisesem

### ISSUE THREAD

**Issue by Ugranziol** [jslefche/piecewiseSEM#217]
Hi,
 I am working on a moderated mediation model. I decided to use piecewisesem package. 
It is a repeated measure design (pre-post), with two mediators and one moderator.
I add a reproducible example:

`
library(piecewiseSEM)
library(nlme)

df<-data.frame(
  ID=rep(1:1215,2),
  Total=rnorm(2430,mean = 17,sd=6),
  Test=rep(c("pre","post"),each=1215),
  Age=rep(rnorm(1215,mean = 17,sd=6),2),
  Mod1=rnorm(2430,mean = 6,sd=4),
  Mod2=rnorm(2430,mean = 6,sd=4)
)

sem_EF<-psem(
  lme(Total~Test:Age+Mod1:Age+Mod2:Age,random=~1|ID,data = df),
  lme(Mod1~Test:Age,random=~1|ID,data = df),
  lme(Mod2~Test:Age,random=~1|ID,data = df)
)

summary(sem_EF)`

Once I run the summary command, I get this error:
"Error in names(B) <- numVars : 'names' attribute [7] must be the same length as the vector [6]"

How can I fix this issue?

Thank you in advance!!

**Comment by jslefche** [comment]
This comes from involving categorical variables in an interaction term. Not sure this is able to be supported right now, so closing. Emailed with some potential solutions
