### ISSUE TITLE
summary() occationally failes when involving GAMs

### ISSUE THREAD

**Issue by KoyaHashimoto** [jslefche/piecewiseSEM#230]
Hello, this is my first post on the issues of piecewiseSEM in github.

I am struggling to explore nonlinear relationships by using the development version of piecewiseSEM package.

I refer to the GAM instructions from the book (https://jslefche.github.io/sem_book/local-estimation.html#extensions-to-non-linear-models), and the code from this book works successfully.
However, some modifications of the example did not work.

```
shipley_psem3_ <- psem(
  gam(x2 ~ s(x1), data = dat2, family = gaussian),
  glm(x3 ~ x2, data = dat2, family = poisson),
  gam(x4 ~ s(x2) + x1, data = dat2, family = poisson), #Modify x2 to smooth curve and add x1
  glm(x5 ~ x3 + x4, data = dat2, family = binomial)
)
summary(shipley_psem3_)
```
This returns an error: 
```
Error in `[<-.data.frame`(`*tmp*`, which(ret$Predictor %in% c("(Intercept)",  : 
  replacement has 2 rows, data has 1
```

In contrast, the following another modification works.
```
shipley_psem3__ <- psem(
  gam(x2 ~ s(x1), data = dat2, family = gaussian),
  glm(x3 ~ x2, data = dat2, family = poisson),
  gam(x4 ~ s(x2), data = dat2, family = poisson), #Modify x2 to smooth curve
  glm(x5 ~ x3 + x4, data = dat2, family = binomial)
)
summary(shipley_psem3__) #No error
```

In addition, in the first example, `rsquared(shipley_psem3_)` works but `coefs(shipley_psem3_)` returns the same error message, so this error seems to arise from the `piecewiseSEM::coefs` function. When `standardized=FALSE`, the `coefs `function successfully works in both cases above.

Koya.

**Comment by jslefche** [comment]
Fixed in 2.2.1
