### ISSUE TITLE
data.table is not supported

### ISSUE THREAD

**Issue by carlos-arnillas** [jslefche/piecewiseSEM#231]
Hello
is it possible to provide support to data.table objects? Here is an example of the problem

```
ll <- list()
dataX <- data.frame(Treatment=sample(c("A", "B", 100, TRUE)), 
                    site_code=sample(c("A", "B", 100, TRUE)),
                    l1=runif(100), l2=runif(100), l3=runif(100))
ll[[1]] <- lm(l1 ~ Treatment + site_code, data=dataX)
ll[[2]] <- lm(l2 ~ Treatment + site_code, data=dataX)
ll[[3]] <- lm(l3 ~ Treatment + site_code, data=dataX)

do.call("psem", c(ll, list(data=as.data.frame(dataX))))
do.call("psem", c(ll, list(data=as.data.table(dataX))))

```

**Comment by jslefche** [comment]
This is on the list, sorry. Please consider converting to `data.frame` and all should be well

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by carlos-arnillas** [comment]
Thanks!
This simple code, in the psem() function, may help meanwhile:
```
if (any(class(x)=="data.table") {
  x <- as.data.frame(x)
  message("data.tables are not supported yet. Transforming an internal copy to data.frame.")
}
```

**Comment by jslefche** [comment]
Added support for tibbles and data.table
