### ISSUE TITLE
sem.model.fits is not working. could you please advise if this function works with the piecewiseSEM package?

### ISSUE THREAD

**Issue by rainforest-stat** [jslefche/piecewiseSEM#235]

**Comment by jslefche** [comment]
The function is deprecated, the new function is `summary` or you can call `rsquared` on the model list (or `psem` object)


____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

From: ***@***.***>
Sent: Sunday, July 4, 2021 12:31 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [jslefche/piecewiseSEM] sem.model.fits is not working. could you please advise if this function works with the piecewiseSEM package? (#235)

External Email - Exercise Caution

**Comment by rainforest-stat** [comment]
> The function is deprecated, the new function is `summary` or you can call `rsquared` on the model list (or `psem` object)
> […](#)
> ____________________________ Jonathan S. Lefcheck, Ph.D. Tennenbaum Coordinating Scientist MarineGEO: https://marinegeo.si.edu/ Smithsonian Institution Phone: +1 (443) 482-2443 [www.jonlefcheck.net<http://www.jonlefcheck.net](http://www.jonlefcheck.net<http://www.jonlefcheck.net)> From: ***@***.***> Sent: Sunday, July 4, 2021 12:31 PM To: ***@***.***> Cc: ***@***.***> Subject: [jslefche/piecewiseSEM] sem.model.fits is not working. could you please advise if this function works with the piecewiseSEM package? (#235) External Email - Exercise Caution — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjslefche%2FpiecewiseSEM%2Fissues%2F235&data=04%7C01%7Clefcheckj%40si.edu%7Cea47765c362d4449439108d93f092a6b%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637610130875804968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yn7Od6NotScgMPMD6lJeuoUp0uFcvWXaD3kWdcIMD0k%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAR4AVZIAR63W2URLKT2GVLTWCEFZANCNFSM47ZK2MUQ&data=04%7C01%7Clefcheckj%40si.edu%7Cea47765c362d4449439108d93f092a6b%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637610130875804968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qQS60GOSKgYqX9%2F0C6UVHRaqfkhH9Sgf2sDTucIANrI%3D&reserved=0>.
