### ISSUE TITLE
GAM and GLM not handling formula specifications 

### ISSUE THREAD

**Issue by plbiella** [jslefche/piecewiseSEM#236]
Hi, 
I noticed that there are some problems when, in the gam function, I specify smoothing parameters. a term like s(variable, k=3) or s(variable, sp=4) or similar is not supported giving errors like: Error in `[.data.frame`(x$data, , vars) : undefined columns selected
This happens only when calling gam within psem, not when calling gam outside piecewiseSEM.

example
set.seed(100)
n <- 100
x1 <- rchisq(n, 7)
mu2 <- 10*x1/(5 + x1)
x2 <- rnorm(n, mu2, 1)
x2[x2 <= 0] <- 0.1
dat2 <- data.frame(x1 = x1, x2 = x2)

library(mgcv)
psem_paolo <- psem(
  gam(x2 ~ s(x1, k=3), data = dat2, family = gaussian)
) 
psem_paolo

The same error Error in `[.data.frame`(x$data, , vars) : undefined columns selected was returned when fitting a GLM with a polynomial term, that is when specifing:
psem_paolo2 <- psem(
  glm(x2 ~ poly(x1, 2), data = dat2, family = gaussian)
) 

thanks

**Comment by seanhardison1** [comment]
I'm also having a similar issue - When I run the GAM example in the bookdown text:

````
library(piecewiseSEM)
library(mgcv)
set.seed(100)
n <- 100
x1 <- rchisq(n, 7)
mu2 <- 10*x1/(5 + x1)
x2 <- rnorm(n, mu2, 1)
x2[x2 <= 0] <- 0.1
x3 <- rpois(n, lambda = (0.5*x2))
x4 <- rpois(n, lambda = (0.5*x2))
p.x5 <- exp(-0.5*x3 + 0.5*x4)/(1 + exp(-0.5*x3 + 0.5*x4))
x5 <- rbinom(n, size = 1, prob = p.x5)
dat2 <- data.frame(x1 = x1, x2 = x2, x3 = x3, x4 = x4, x5 = x5)

psem(
  gam(x2 ~ s(x1), data = dat2, family = gaussian),
  glm(x3 ~ x2, data = dat2, family = poisson),
  gam(x4 ~ x2, data = dat2, family = poisson),
  glm(x5 ~ x3 + x4, data = dat2, family = binomial)
)
````

I'm returned with the error: `Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 100`

 it looks like it's because the internal function `GetSingleData` doesn't have a way to extract data from GAM class objects. 

````
library(mgcv)
mod1 <- gam(x2 ~ s(x1), data = dat2, family = gaussian)
piecewiseSEM:::GetSingleData(mod1)

mod2 <- glm(x3 ~ x2, data = dat2, family = poisson)
piecewiseSEM:::GetSingleData(mod2)

# GetSingleData----
model <- mod1
dat <- data.frame()
switch(class(model)[1], phylolm = {
  stop("Please provide `data =` argument to `psem`.", call. = FALSE)
}, phyloglm = {
  stop("Please provide `data =` argument to `psem`.", call. = FALSE)
}, lm = {
  dat <- eval(getCall(model)$data, environment(formula(model)))
}, negbin = {
  dat <- eval(getCall(model)$data, environment(formula(model)))
}, sarlm = {
  dat <- eval(getCall(model)$data, environment(formula(model)))
}, glm = {
  dat <- model$data
}, glmmPQL = {
  dat <- model$data
}, pgls = {
  dat <- model$data
}, lmerMod = {
  dat <- model@frame
}, glmerMod = {
  dat <- model@frame
}, lmerModLmerTest = {
  dat <- model@frame
}, merModLmerTest = {
  dat <- model@frame
}, gls = {
  dat <- nlme::getData(model)
}, lme = {
  dat <- nlme::getData(model)
})
dat

````

It looks like the method to extract data from the model in the environment works for GAM objects, so maybe simply adding 

````
, gam = {
  dat <- eval(getCall(model)$data, environment(formula(model)))
}
````

to `GetSingleData` is a potential fix?

**Comment by jslefche** [comment]
Fixed

**Comment by fezoz** [comment]
Hi,

I just wanted to flag that this hasn't been fixed. I just attempted it with the dummy data provided by @plbiella as well as my own and I got the same error:

"Error in `[.data.frame`(x$data, , vars) : undefined columns selected"

thanks
