### ISSUE TITLE
getDAG function doesn't recognize loops in the model

### ISSUE THREAD

**Issue by davmarza** [jslefche/piecewiseSEM#239]
Hi, I'm new to piecewiseSEM and I'm doing some research on the Basis Set and d-separation test. Thanks a lot for writing this, it's really helpfull! 
I'm using getDAG to obtain the DAG from my model list, but I intentionally tested the function with a loop (so that the model is non-recursive) and the function doesn't recognize the issue. 
I think that the problem is in the last if statement:

  if (sum(colSums(amat) > 0) < 1 & igraph::is_dag(igraph::graph_from_adjacency_matrix(amat))) 
    stop("Model is non-recursive. Remove feedback loops!", call. = FALSE)

I tried to edit the code like so and it recognize when a loop is present and stop the function

  if(!igraph::is_dag(igraph::graph_from_adjacency_matrix(amat))){
    stop("Model is non-recursive. Remove feedback loops!", call.=TRUE)}

There's is something I'm missing about this? Thank you for your time

**Comment by jslefche** [comment]
Good catch, fixed
