### ISSUE TITLE
NA for r^2 value

### ISSUE THREAD

**Issue by nitinra** [jslefche/piecewiseSEM#240]
Hello,

I am trying to build a psem model for understanding the effects of herbivory in year t and it's effects on plant reproduction in year t+1. 

Here is the code for my model:
`model<-psem(
  glm(volume05~totmeri+sun+soil+spruce+webcount,family=gaussian(link="log"),na.action=na.fail,data=data1),
  glm(webcount~totmeri, family=poisson(link="log"),na.action=na.fail, data=data1),
  glm(seed05~volume05+seed04+webcount+sun+spruce, family=poisson(link="log"),na.action=na.fail,data=data1),
  data=data1
)`

However, I am getting a NA value for the r^2 value for the seed05. 

  
<img width="424" alt="Screen Shot 2021-09-02 at 9 22 37 PM" src="https://user-images.githubusercontent.com/70153351/131936312-06bb72cc-39fc-4b52-bbae-3a42b5d6df3b.png">

Here is my data:`https://drive.google.com/file/d/13B2n8BwqGATAuSFvoQIl0vObCnabPi0q/view?usp=sharing`.

**Comment by jslefche** [comment]
Appears to be fixed in 2.2.1
