### ISSUE TITLE
psem not working with pgls models

### ISSUE THREAD

**Issue by Fabiogeography** [jslefche/piecewiseSEM#243]
Hi, 

when running psem, dSep, fisherC with pgls models as below I get an error:

dat.pgls <- comparative.data(tree1, dat, names.col="sp.phylo") 
pm1b <- pgls(yr1_1 ~ rsEURm2_t1 + rsEURm2_t2, data=dat.pgls)
pm2b <- pgls(rsUSAm2_t ~ rsEURm2_t1 + rsEURm2_t2 + yr1_1 + yr1_2  + growthTree + growthShrub, data=dat.pgls)
px <- psem(pm1b, pm2b)

Error:
in as.data.frame.default(data) : 
  cannot coerce class ‘"comparative.data"’ to a data.frame

I think I've traced this to a seeming incompatability between the output of pgls and the way psem functions obtain the data from the model object. For example, in GetData:

data.list <- lapply(modelList, piecewiseSEM:::GetSingleData) ## returns the same number comparative.data objects as the number of models in modelList
...
if (all(sapply(data.list, class) == "comparative.data")) ## yes classes of all list elements are 'comparative.data'
    data <- data.list[[1]] ## This returns a comparative.data object. Using data.list[[1]]$data returns a data frame.

So I think GetData should be returning a single data frame, and I can make it do that by the modification in my comment above, however then running summary(px) then complains that "data is not a 'comparative' data object".

If I run the following:
px <- psem(pm1b, pm2b, data=dat.pgls) ## This works
summary(px) ## This fails with the same error message as above. It doesn't use the GetData function, but the problem seems to be the same.

I'm using R 4.1.1, piecewiseSEM 2.1.1 and caper 1.0.1. I had the same problems when  using R 3.6.2 and older package versions.

Hope I'm not just making a silly mistake.

**Comment by xuejing2021** [comment]
Same question......Waiting for the answerer！

**Comment by jebyrnes** [comment]
Can you put up a reprex?

**Comment by xuejing2021** [comment]
Hi, 
I  used two methods of "gls" and "pgls".
Averages<- read.csv("data_total.csv")
tree = read.tree("tree.tre")
.............
light_sem = psem(
   gls(RLG ~ mass + Shape+ LF + DM, correlation = corBrownian(1, tree,form=~species),  na.action = na.omit, data=Averages),
   gls(mass ~ LF + DM, correlation = corBrownian(1, tree,form=~species), na.action = na.omit,data=Averages),
   gls(Shape ~ LF + DM + Rclass, correlation = corBrownian(1,tree,form=~species), na.action = na.omit, Averages)
)
summary(light_sem)
#
error:
 n as.data.frame.default(data, optional = TRUE) :  cannot coerce class ‘"function"’ to a data.frame
########
and 
rownames(Averages) = Averages$species
tree$node.label=1:tree$Nnode
light_sem_merge = comparative.data(tree, Averages, names.col = "species")

light_sem = psem(
  pgls(RLG ~ mass + Shape+ LF + DM, data=light_sem_merge ),
  pgls(mass ~ LF + DM, data=light_sem_merge ),
  pgls(Shape ~ LF + DM,  data= light_sem_merge )
)
#
error:
Error in as.data.frame.default(data) : cannot coerce class ‘"comparative.data"’ to a data.frame

I'm using R 4.1.0, piecewiseSEM 2.1.2 , caper 1.0.1. and ape 5.5. I had the same problems when using Rstudio in macOS and Windows systems.

I have the same sigh: Hope I'm not just making a silly mistake.

**Comment by xuejing2021** [comment]
I  had to deal with the question.   I used the old version 1.2.1 of piecewiseSEM to run all analyses.

**Comment by jslefche** [comment]
Apologies, I have not gotten around to reimplementing pgls. The older version should work or there are other packages specifically for phylogenetic SEM

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
