### ISSUE TITLE
psem function not working?

### ISSUE THREAD

**Issue by Sophie-McLeod96** [jslefche/piecewiseSEM#244]
Hiya,

Sorry if this is a really stupid question but I can't seem to find an answer for it.

When I try to run my code I get this error.
_Error in psem(lme(red ~ seed + pop + lynx + wolf + sheep, random = ~1 |  : 
  could not find function "psem"_

I have definitely downloaded the piecewiseSEM package and and loaded it from my library. 
I have restarted R and my laptop incase it just had't loaded quite right.

Do you think you could help with this please? 

Sorry!

Sophie

**Comment by Sophie-McLeod96** [comment]
Hi Jon,

Thank you for this I have reinstalled the package and I note that the issue seems to be that to nloptr was not installed and I needed this one too :)
But honestly thank you so much for responding to my question so quickly! I really appreciate that!

All the best,

Sophie

**Comment by jslefche** [comment]
Happy coding!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

________________________________

**Comment by Sophie-McLeod96** [comment]
Haha! Its all very new and to be honest quite exciting :D 
I think I will be using these SEM models a lot for my thesis so I better learn quickly!

If you have any tips on how to best display these models as plots I’m all ears :D

Thank you

Sophie

**Comment by jslefche** [comment]
Honestly, powerpoint. The graphing capabilities for these kinds of models are limited in R. Other progams include illustrator and free alternatives, like Inkscape

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
