### ISSUE TITLE
Fitted values from pSEM

### ISSUE THREAD

**Issue by frandadamo** [jslefche/piecewiseSEM#251]
Hi all,

I’d have a super easy question to ask, please.

How do you get fitted values from a pSEM? I would like to plot residuals vs. fitted values. I am aware that there are many other pSEM model diagnostic tools (e.g., chi-square test, root mean square error of approximation, standardized root mean square residual, comparative fit index, AIC, BIC, etc.), but how about fitted values? The `residuals` and `part.residuals` functions do not seem to answer this. The closest I could get is #197, but I was wondering if there is an option within the piecewiseSEM package.

Thanks a lot (sorry for the silly question),

Francesco

**Comment by jebyrnes** [comment]
As residuals are model by model, you can always lapply through your psem object to get residuals for each model.

**Comment by jebyrnes** [comment]
Er, sorry, same answer but use the fitted function!

**Comment by frandadamo** [comment]
Hi Jarrett,

Thanks a lot for your replies. I am not sure I understand your solution. Could you please formulate it for dummies? Are you suggesting what you wrote in this https://github.com/jslefche/piecewiseSEM/issues/197#issuecomment-566638607

Thanks again!
