### ISSUE TITLE
In B * (sd.x/sd.y) :   longer object length is not a multiple of shorter object length

### ISSUE THREAD

**Issue by Canderson156** [jslefche/piecewiseSEM#253]
I'm stumped by this warning message. It seems to occur when I use a categorical variable in my model. Any thoughts?

In B * (sd.x/sd.y) :
  longer object length is not a multiple of shorter object length

**Comment by jslefche** [comment]
Should be ok if you get an output

Have you updated to the development version? That may also fix it

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

From: ***@***.***>
Sent: Monday, April 11, 2022 3:06 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [jslefche/piecewiseSEM] In B * (sd.x/sd.y) : longer object length is not a multiple of shorter object length (Issue #253)

External Email - Exercise Caution

I'm stumped by this warning message. It seems to occur when I use a categorical variable in my model. Any thoughts?

In B * (sd.x/sd.y) :
longer object length is not a multiple of shorter object length

**Comment by Canderson156** [comment]
The reason why I was wondering about the error code is that I'm trying to use the package semEff and am having a lot of issues getting it to work. Likely the issues are coming from that package, but I thought if I was getting this error it also seemed like something to investigate as a possible cause.

I tried downloading the development version, but now I'm getting errors running my code that uses the %~~% operator. 
Error in wet_sedge %~~% high_shrub : object 'wet_sedge' not found
Works fine if I remove this and all %~~% lines, and the same predictors are found in the main models

**Comment by jslefche** [comment]
In the absence of a reprex, closing for now
