### ISSUE TITLE
Error in plot.psem(mod, return = TRUE): could not find function "plot.psem"

### ISSUE THREAD

**Issue by hrdawson** [jslefche/piecewiseSEM#255]
The `plot.psem` function appears to be down. The reproducible example from the `piecewiseSEM` reference page shows the error message: https://jslefche.github.io/piecewiseSEM/reference/plot.psem.html

```
data(keeley)
mod <- psem(
  lm(rich ~ cover, data=keeley),
  lm(cover ~ firesev, data=keeley),
  lm(firesev ~ age, data=keeley),
  data = keeley)
plot(mod)

### More customized plot
keeley_graph <- piecewiseSEM::plot.psem(mod, return=TRUE)
#> Error in plot.psem(mod, return = TRUE): could not find function "plot.psem"
```

This happened for me both on the CRAN version of `piecewiseSEM` and the developer version. 

(Edit: Markdown formatting issues, sorry)

**Comment by hrdawson** [comment]
**Update:** I've worked on uninstalling and reinstalling `piecewiseSEM` and `DiagrammeR`. I still get the above error message, but if I manually load the `plot.psem` function from GitHub (just cut and paste the code into my console from https://github.com/jslefche/piecewiseSEM/blob/master/R/plot_psem.R), the error message changes to
`Error in get_calling_fcn() : could not find function "get_calling_fcn"` 
I've tried to locate code for `get_calling_fcn()`, which looks to be code from `DiagrammeR`, but my rudimentary package coding skills are not enough to find the original code...

**Comment by jslefche** [comment]
Fixed with roxygenise
