### ISSUE TITLE
`stdCoefs` not returning values for transformed variables when in formula

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#256]
```
data <- data.frame(
  y = runif(50),
  x = runif(50),
  z = runif(50),
  a = runif(50)
)


modelList <- psem(lm(log10(y+1) ~ sqrt(x), data),
                  lm(z ~ log10(y + 1), data))

coefs(modelList)

```

**Comment by saraswaminathan** [comment]
Hypothetical question related to this. Say you have several non-normal responses, and a couple that are normal within your psem. Most of my variables are highly right skewed biomass data. Glmer is an option, but psem won’t return standardized residuals for the appropriate family/link for my data. Transformation is an option, but unsure whether it’s better to universally transform all the variables in the same way, or tailor transformations for individual variables. If transforming variables, is it okay to interpret standardized coefficients as-is, or is some sort of back transformation necessary? Thank you

**Comment by jslefche** [comment]
If you transform the response, then the standardized coefficients will be in units of SD of the transformed response. Same goes for predictors

GLMER is a special case since the link function linearizes the response, but there are additional sources of variance depending on the error distribution. So you will not get the same values if you, say, log-transform the response vs. if you fit a GLMER

HTH,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
Not sure what was happening here: code was stripping transformations from vector of coefficients and then couldn't match with the summary table from the model. So I took it out...hope it doesn't break something
