### ISSUE TITLE
summary fails when the same smooth terms in different sub-models have different basis dimension

### ISSUE THREAD

**Issue by seanhardison1** [jslefche/piecewiseSEM#279]
This is more of a public service announcement than an issue, but if you're including the same non-linear terms in different sub-models, the `summary` function will fail if you've specified the repeated smooth term with different basis dimensions. This makes sense, but maybe future iterations could throw an error message in this situation.

for example (borrowed simulation from a different issue)

```
A <- rnorm(100,mean = 10, sd = 5)
B <- rnorm(100,mean = 10, sd = 5)
C <- round((0.25*A + 0.25*B + rnbinom(100,mu=10,size=2)),0)
D <- 0.1*A + 0.25*B + 0.5*C + rnorm(100)
E <- round(0.5*(C) + 0.5*(D) + rnbinom(100,mu=5,size=2),0)
dat <- data.frame(A,B,C,D,E)


gam.C <- mgcv::gam(C ~ s(A,k=3) + s(B,k=3),data=dat, family=negbin(1.8))
gam.D <- mgcv::gam(D ~ s(A,k=3) + s(B,k=3) + s(C,k=3),data=dat)
gam.E <- mgcv::gam(E ~ s(C,k=3) + s(D,k=3),data=dat, family=negbin(14.6))


SEM.gam <- psem(gam.C,gam.D,gam.E)
summary(SEM.gam)# works

gam.C <- mgcv::gam(C ~ s(A,k=3) + s(B,k=3),data=dat, family=negbin(1.8))
gam.D2 <- mgcv::gam(D ~ s(A,k=4) + s(B,k=3) + s(C,k=3),data=dat) #note k = 4 in this line but k = 3 in previous
gam.E <- mgcv::gam(E ~ s(C,k=3) + s(D,k=3),data=dat, family=negbin(14.6))


SEM.gam2 <- psem(gam.C,gam.D2,gam.E)
summary(SEM.gam2) # fails without context
```

**Comment by allisonstegner** [comment]
A clear(er) error message would be very helpful! I spent a very, very long time trying to figure this out because the error message I received related to the variable names ("in str2lang(x) : <text>:1:380: ") and didn't seem to have any obvious connection to the GAM or the basis dimensions.
