### ISSUE TITLE
Unsupported family error

### ISSUE THREAD

**Issue by rungec** [jslefche/piecewiseSEM#289]
I get this error 'Error in rsquared.glmerMod(i, method): Unsupported family!' when I run summary() on the psems below. 
It has glmers with Gamma, gamma (log link), gaussian (log link), gaussian (inverse link) and poisson families.

Do you have any suggestions for how to resolve? 
Thanks,
Claire

dens_cattle_m1 <- psem(glmer(Shrub_cover ~ Cattle + Rain_long + Tree_cover + (1 | Trip/site_code), data=mod_df, family=Gamma, control=glmerControl(optimizer="optimx", optCtrl=list(method='nlminb'))),
                       glm(Ground_cover ~ Cattle + Rain_short + Tree_cover, family=Gamma,  data=mod_df),
                       glmer(Flowering ~ Shrub_cover + season + Rain_short + (1 | site_code), family=gaussian(link="log"), data=mod_df, control=glmerControl(optimizer="optimx", optCtrl=list(method='nlminb'))),
                       glmer(Fruiting_shrub ~ Shrub_cover + Rain_short + (1 | site_code), family=Gamma(link="log"), data=mod_df),
                       glmer(Seeding_grass ~ Ground_cover + (1 | Trip/site_code), data=mod_df, family=gaussian(link="log"), control=glmerControl(optimizer="optimx", optCtrl=list(method='nlminb'))),
                       glmer(Plant_diversity ~ Rain_long +  Cattle + Ground_cover + Shrub_cover + (1 | Trip/site_code), data=mod_df, family=gaussian(link="inverse"), control=glmerControl(optimizer="optimx", optCtrl=list(method='nlminb'))),
                       glmer(Richness_cum ~ Plant_diversity + Tree_cover + Seeding_grass + Fruiting_shrub + Flowering + (1 | Trip/site_code), data=mod_df, family=poisson))

dens_cattle_m2 <- update(dens_cattle_m1, Shrub_cover %~~% Ground_cover)

**Comment by DarwinMayhew** [comment]
I've had the same error. The models seem to work well outside of psem() but not while inside. Specifically gamma (log link) and gaussian (log link) in lme4 models with non-integer numbers.

**Comment by rungec** [comment]
Interesting, DarwinMayhew. I solved by running psem a mix of poisson and gaussian family models, which were conceptually appropriate to my untransformed dataset, though leaves me with questions around the relative contribution of variables which have different ranges - was hoping to solve by range standardisation.
