### ISSUE TITLE
how to declare correlation and problems during instalation

### ISSUE THREAD

**Issue by paternogbc** [jslefche/piecewiseSEM#34]
Hi, thanks for this nice contribution.

I would like to know if this packages allows the inclusion of correlation between two variables (A,B) or if all paths must be causal? I notice that in the examples explored in the manuscript there are only causal relationships.

I am working on a phylogenetic path analysis where I want to declare simple correlations between some pairs of variables (usually a two-side arrow in path diagrams) in the model. Could you please give me some advice on that?

Further I am getting the following error while installing your package on R v3.2:
> Warning: replacing previous import by ‘ggplot2::unit’ when loading ‘Hmisc’
Warning: replacing previous import by ‘ggplot2::arrow’ when loading ‘Hmisc’
Warning: replacing previous import by ‘scales::alpha’ when loading ‘Hmisc’
Error in eval(expr, envir, enclos) : 
  não foi possível encontrar a função "eval"
Error : unable to load R code in package ‘Hmisc’
ERROR: lazy loading failed for package ‘Hmisc’
* removing ‘/home/paternogbc/R/x86_64-pc-linux-gnu-library/3.2/Hmisc’
Warning in install.packages :
  installation of package ‘Hmisc’ had non-zero exit status
ERROR: dependency ‘Hmisc’ is not available for package ‘lmerTest’
* removing ‘/home/paternogbc/R/x86_64-pc-linux-gnu-library/3.2/lmerTest’
Warning in install.packages :
  installation of package ‘lmerTest’ had non-zero exit status
ERROR: dependency ‘lmerTest’ is not available for package ‘piecewiseSEM’
* removing ‘/home/paternogbc/R/x86_64-pc-linux-gnu-library/3.2/piecewiseSEM’
Warning in install.packages :
  installation of package ‘piecewiseSEM’ had non-zero exit status

Thanks in advance!

**Comment by jslefche** [comment]
Yes, the argument `corr.errors = ` removes correlated variables from the d-sep tests and instead calculates a correlation test and P=value. This is a crude implementation and I'm working on a more elegant solution

**Comment by paternogbc** [comment]
Dear @jslefche,

I am sorry for this late reply. Your answer got unnoticed in my in-box.
I have tried your approach, however, I still cant declare correlated variables. 
See my example bellow:

> com.dat <-  comparative.data(data = dat21$data, dat21$phy , "sp")
> m2_1 <- pgls(AGr ~ Lherb + Lsla + Lseed + Lheight, com.dat, lambda = "ML")
> m2_2 <- pgls(Lherb ~ Lsla + Lseed + Lheight, com.dat, lambda = "ML")
> modlist = list(m2_1, m2_2)
> sem.fit(modlist, dat21, corr.errors = Lsla ~~ Lseed)

But I get this error:
> Error in strsplit(j, "~~")

Any suggestion,
Thanks once again.

**Comment by jebyrnes** [comment]
You are missing quotes.

    sem.fit(modlist, dat21, corr.errors = "Lsla ~~ Lseed")

**Comment by jslefche** [comment]
@jebyrnes is, as usual, correct. Closed

**Comment by paternogbc** [comment]
Thanks for the fast feedback.
I had also tried that, but then I got this error:

> Error in cor(data[, corr.vars[1]], data[, corr.vars[2]], use = "complete.obs") : 
  'x' must be numeric

Any idea? 
Maybe is my data?
