### ISSUE TITLE
offsets in glm.nb() models treated as predictors in sem.fit()

### ISSUE THREAD

**Issue by srgriffin108** [jslefche/piecewiseSEM#35]
when offsets are included within glm.nb() models in the model list, sem.fit treats the offsets as predictors and includes them in the list of missing paths in the output, which also affects the Fisher's C and AIC values.  In glm.nb, offsets must be included within the model formula. Example below:

model_list=list(
response1= glm(response1 ~  predictor1 , data=Data)
response2= glm.nb(response2 ~  response1 + predictor2 + offset(log(variable)), data=Data)
)

sem.fit(model_list, Data)

**Comment by jslefche** [comment]
Fixed. (Example below)

data = data.frame(
  response1 = sample(1:100, 100, replace = T),
  response2 = sample(1:100, 100, replace = T),
  predictor1 = runif(100),
  predictor2 = runif(100),
  variable = sample(1:10, 100, replace = T)
)

library(MASS)

modelList =list(
  response1= glm(response1 ~ predictor1 , data=data),
  response2= glm.nb(response2 ~ response1 + predictor2 + offset(log(variable)), data=data)
)

filter.exogenous(modelList)

sem.fit(modelList, data)

**Comment by srgriffin108** [comment]
Amazing, thanks so much!  Great news.

I hope you have a good time over the holidays!

Sean

On Wed, Dec 23, 2015 at 11:58 AM, Jon Lefcheck <notifications@github.com>
wrote:

> Closed #35 <https://github.com/jslefche/piecewiseSEM/issues/35>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jslefche/piecewiseSEM/issues/35#event-499594921>.
>



-- 
Sean Griffin
Ph.D. Student
Rutgers University-New Brunswick
(301) 706-7467
