### ISSUE TITLE
Interactions in sem.lavaan

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#36]
Interactions need to be hand calculated since lavaan does not play nice with interactions

**Comment by jslefche** [comment]
Not sure if this is an issue, need to check with Jarrett:

```
data = data.frame(
  x1 = runif(100, 0, 1),
  x2 = runif(100, 0, 1),
  x3 = runif(100, 0, 1),
  x4 = runif(100, 0, 1)
)

modelList = list(
  lm(x1 ~ x2, data),
  lm(x3 ~ x1 * x2, data),
  lm(x4 ~ x3, data)
)

sem.fit(modelList, data)

sem.lavaan(modelList, data)

data$x1_x2 = data$x1 * data$x2

model = '
  x1 ~ x2
  x3 ~ x1 * x2
  x4 ~ x3
'

library(lavaan)

sem(model, data)

model2 =  '
  x1 ~ x2
  x3 ~ x1_x2
  x4 ~ x3
'

sem(model2, data)
```

**Comment by jebyrnes** [comment]
Yep, they will need to be hand-calculated for lavaan. Then again, perhaps they can be extracted from model objects in many cases? Ditto transformed variables?

The annoying issue will come in in the accounting for covariances between linear variables and their nonlinear offspring. But, c'est la vie.

**Comment by jslefche** [comment]
Added argument `compute.int = TRUE` to hand calculate interactions and pass them to `lavaan::sem`
