### ISSUE TITLE
Odd missing paths output

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#37]
Using the Day 1 example from http://byrneslab.net/teaching/sem/ produces some odd output from piecewiseSEM's missing paths function. Load the Keeley data at the above URL and the piecewiseSEM library, and then run the following:

    modList <- list(
      lm(abiotic ~ distance, data=keeley),
      lm(hetero ~ distance, data=keeley),
      lm(rich ~ abiotic + hetero, data=keeley))

    #what paths are missing?
    sem.missing.paths(modList, data=keeley)

This produces output where distance is sometimes included twice:

                                missing.path  estimate std.error DF crit.value      p.value
    1     rich ~ distance + hetero + abiotic 0.6404318 0.1564575 86   4.093329 9.564005e-05
    2 abiotic ~ hetero + distance + distance 8.9334404 6.7189669 87   1.329585 1.871306e-01

What's up with distance being in twice in row 2?

**Comment by jebyrnes** [comment]
N.B. Fletcher noticed this. Blame him. HA!

**Comment by jslefche** [comment]
Yup all fixed in latest version so update accordingly! 

PS isn't this Fletcher's second time taking this course??
