### ISSUE TITLE
sem.coeff does not standardize coefficients when offsets are included in the models

### ISSUE THREAD

**Issue by srgriffin108** [jslefche/piecewiseSEM#40]
I am trying to extract the standardized coefficients from the model set, but when I set standardize="scale" I receive the error warning "Transformations detected in the formula! This may produce invalid scaled values Store transformations as new variables, and re-specify the models." Do you think that this error is due to the offsets within the model?

**Comment by jslefche** [comment]
Fixed

**Comment by jslefche** [comment]
Seems as if this doesn't work if variables are transformed INSIDE the offset:

```
library(piecewiseSEM)

data = data.frame(
  y = runif(100),
  x1 = runif(100),
  x2 = runif(100)
)

model = lm(y ~ x1 + offset(log(x2)), data)

sem.coefs(model, data, standardize = "scale") # error

data$log.x2 = log(data$x2)

model2 = lm(y ~ x2 + offset(log.x2), data)

sem.coefs(model2, data, standardize = "scale") # no error
```

**Comment by jslefche** [comment]
Looks like I got this one...maybe...
