### ISSUE TITLE
Including corr.errors with sem.coefs gives an error

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#41]
```
> sem.coefs(sem_mod_nlme, data=exp_data_func, corr.errors="belowbiomass_g~~abovebiomass_g")
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
```

Although corr.errors is in the function help file as a possible argument.

**Comment by jslefche** [comment]
E.g., 

library(MASS)


data = data.frame(
  y = sample(1:100, 100, replace = T),
  x1 = runif(100), 
  x2 = sample(letters[1:4], 100, replace = T), 
  x3 = runif(100), 
  x4 = runif(100), 
  x5 = runif(100)
)

data[c(4, 36, 54, 77), 3] = NA

modelList = list(
  glm.nb(y ~ x1 + x2 + x5, data),
  lm(x3 ~ x4, data)
)

sem.coefs(modelList, data, standardize = "scale")
sem.coefs(modelList, data, corr.errors = "x5 ~~ x4")

**Comment by jslefche** [comment]
Correlated errors handled differently in 2.0
