### ISSUE TITLE
Standardizing coefficients borks with a categorical variables

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#42]
I was running an analysis with a categorical variable using NLME and get the following borked error when I use standardize="scale"

    > sem.coefs(sem_mod_nlme, data=exp_data_func, standardize="scale")
    Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric
    In addition: Warning message:
    In if (class(data) == "comparative.data") newdata = data$data else newdata = data :
      the condition has length > 1 and only the first element will be used

Hrm........

**Comment by jslefche** [comment]
Hmm seems to work on this end. Can you provide a reproducible example?

E.g., 

library(MASS)


data = data.frame(
  y = sample(1:100, 100, replace = T),
  x1 = runif(100), 
  x2 = sample(letters[1:4], 100, replace = T), 
  x3 = runif(100), 
  x4 = runif(100), 
  x5 = runif(100)
)

data[c(4, 36, 54, 77), 3] = NA

modelList = list(
  glm.nb(y ~ x1 + x2 + x5, data),
  lm(x3 ~ x4, data)
)

sem.coefs(modelList, data, standardize = "scale")

**Comment by jslefche** [comment]
Figured it out -- had to do with factors being stored as characters. Fixed!
