### ISSUE TITLE
Interactions & main effects in basis set

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#44]
Should interaction terms be evaluated independently of their main effects? 

https://stats.stackexchange.com/questions/11009/including-the-interaction-but-not-the-main-effects-in-a-model

**Comment by jslefche** [comment]
What do you think @jebyrnes? Should y ~ x1:x2 be evaluated independently of x1 and x2 in d-sep tests. For that matter, should x1:x2 ~ x3 be included in the basis set as well??

**Comment by jebyrnes** [comment]
Argh. This old question. I mean, I don’t think they should be evaluated independently.  I’m not convinced they should be included at all in the basis set, to be honest. Did Bill Shipley or Jim Grace not give you a solid answer on this? I recall a paper of Shipley’s a few years back where a squared term was used as its own node in the basis set, but I was not clear if it was treated independently or not.

On Feb 1, 2016, at 3:11 PM, Jon Lefcheck <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you think @jebyrnes<https://github.com/jebyrnes>? Should y ~ x1:x2 be evaluated independently of x1 and x2 in d-sep tests. For that matter, should x1:x2 ~ x3 be included in the basis set as well??
