### ISSUE TITLE
Package support wishlist

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#47]
Current requests:

-`metafor`
-MRM() in `ecodist`

**Comment by jebyrnes** [comment]
This would be mind-blowing.

On Feb 16, 2016, at 9:45 AM, Jon Lefcheck <notifications@github.com<mailto:notifications@github.com>> wrote:


For meta-analysis and SEM

-

**Comment by kristyleah** [comment]
New request:

Beta regression with gamlss package

**Comment by jslefche** [comment]
glmmTMDB

**Comment by jslefche** [comment]
glmmadmb

**Comment by jbried** [comment]
New request:

Multivariate GLM from mvabund package
