### ISSUE TITLE
glmmTMB

### ISSUE THREAD

**Issue by MichaelRatajczak** [jslefche/piecewiseSEM#65]
Hi Jon,

It would be great if you could add support for the glmmTMB model class.

Magnusson A, Skaug H, Nielsen A, Berg C, Kristensen K, Maechler M, van Bentham K, Bolker B and Brooks M (2016). glmmTMB: Generalized Linear Mixed Models using Template Model Builder. R package version 0.0.2, https://github.com/glmmTMB

Kind regards,
Michael

**Comment by jslefche** [comment]
Everything should work now except `sem.model.fits` which is ironic given the function in the package to get R^2s is adopted from this package. Will work on that and hopefully provide an update soon.

Example:
```
library(glmmTMB)

data = data.frame(
  y = sample(0:1, 100, replace = T),
  y2 = sample(0:1, 100, replace = T),
  y3 = sample(0:1, 100, replace = T),
  random = letters[1:5]
)

modelList = list(
  glmmTMB(y2 ~ y + (1|random), family = "binomial", data),
  glmmTMB(y3 ~ y2 + (1|random), family = "binomial", data)
)

sem.basis.set(modelList)

sem.missing.paths(modelList, data)

sem.coefs(modelList, data)

sem.model.fits(modelList, data) # does not work yet!
```

**Comment by MichaelRatajczak** [comment]
Hi Jon,

Thanks for the update, I'm glad things are progressing. glmmTMB looks promising so it's really good that piecewiseSEM will support it.

Did you have a look at the code? https://github.com/glmmTMB/glmmTMB/blob/master/misc/rsqglmm.R
Not sure if it will be of any help, but Ben Bolker wrote that he also incorporated some code form MuMin.

**Comment by jslefche** [comment]
Added to wishlist since this is going to get back-burnered for 2.0

**Comment by padluq** [comment]
Hi Jon,
Thanks for all the hard work on this package!  I wanted to ask whether v2.0.2 explicitly supports glmmTMB models?   According to the documentation it does not.  

When I try running psem with a glmmTMB model, I receive an error and knowing whether it's supported would help me decide how much time to devote to overcoming the error.

Thank you,
Adrian

**Comment by jslefche** [comment]
Hi Adrian,

Unfortunately it does not support glmmTMB right now, but it is on the list. Alas, I have no ETA for you atm, so may be best to forge ahead with an alternative.

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by padluq** [comment]
Hi Jon,
Thanks so much for your response and all your hard work on the package.

Best regards,
Adrian
________________________________

**Comment by Caladas** [comment]
Hi Jon, 

As far as I understand from previous posts, glmmTMB was in the works to be added into piecewiseSEM a few years ago. Has it been added since? I'm trying to run some neg binom models and keep getting some errors when using psem and glmmTMB-models. 

All the best, and great work! 

//David

**Comment by jslefche** [comment]
Hi David, not yet, but hoping for the end of this calendar year

J

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by nas258** [comment]
Hi John,

I wanted to check in if the piecewiseSEM package now supports glmmTMB?

Thanks for your hard work!

**Comment by jslefche** [comment]
Indeed, the package does support glmmTMB now!
  
​
  
  
  
=================
  
​Jonathan Lefcheck, Ph.D.
  
​Research Scientist
  
​Integration and Application Network
  
​University of Maryland Center for Environmental Science
  
​https://jonlefcheck.net

**Comment by nas258** [comment]
Hi John,

Sorry for the bother, but to your previous comment, it seems that the piecewiseSEM package doesn't support the family = tweedie(link = "log") to calculate standardized coefficients.

I get this warning message when running the summary of my model:
"Warning messages:
1: In GetSDy(i, newdata, standardize, standardize.type) :
  Family or link function not supported: standardized coefficients not returned"

I get this error when I try to plot the model:
"Error in round(ctab$Std.Estimate, digits) : 
  non-numeric argument to mathematical function"

I just want to confirm, does the package support Tweedie distributions/log links, or is this an issue on my end?

Thank you for your time and help.
