### ISSUE TITLE
handle functions applied to predictors in model call

### ISSUE THREAD

**Issue by kdarras** [jslefche/piecewiseSEM#66]
GLMMs using lme4 are quite fashionable, but their predictors very often require scaling to avoid convergence issues or simply to get results at all.

However scaling a predictor creates a new variable in piecewiseSEM, as both the "predictor"and "scale(predictor)" versions of the same predictor will show up in the mandala, the missing paths, etc.

This makes piecewiseSEM almost impossible to use for normal count data of organisms, sadly.

Imagine you have a working glmer with poisson link, or a glmer.nb. Alternatively, you could use a normal lmer but then the response needs to be log-transformed and then you run into the same problem again because the response variable will get separated in two different variables afterwards. Even if you save the log-transformed variable as a new variable, you will need a non-transformed one for when it is a predictor.

If there is any workaround, I would be happy to know.

**Comment by jslefche** [comment]
Hi Kevin,

Can't seem to reproduce. See below... can you give an example?

```
library(lme4)
library(piecewiseSEM)

data = data.frame(
  y = sample(0:1, 100, replace = T),
  x1 = runif(100, 0, 100),
  x2 = runif(100, 0, 100),
  random = letters[1:2]
)

# Store glmm
model = glmer.nb(y ~ scale(x1) + x2 + (1 | random), data) # ignore warning

# Get output
sem.coefs(model, data) # only 1 output for x1

# Plot results
sem.plot(model, data) # only 1 output for x1
```

**Comment by kdarras** [comment]
```
library(lme4)
library(piecewiseSEM)

data = data.frame(
  y = sample(0:1, 100, replace = T),
  x1 = runif(100, 0, 100),
  x2 = runif(100, 0, 100),
  x3 = runif(100, 0, 100),
  random = letters[1:2]
)

# Store glmm
model.list = list(glmer.nb(y ~ scale(x1) + x2 + (1 | random), data)
                  ,glmer.nb(x1 ~ x3 + x2 + (1 | random), data))# ignore warning

# Get output
sem.coefs(model.list, data) # only 1 output for x1

# Plot results
sem.plot(model.list, data) # only 1 output for x1

```

**Comment by jslefche** [comment]
Gotcha. In the coefficients output, `x1` will show up multiple times regardless of how it is transformed, because this is simply a condensed version of the summary output.

E.g., 
```
# Get output
sem.coefs(model.list, data) # only 1 output for x1

# response predictor     estimate   std.error p.value 
# 1        y        x2 -0.003441934 0.004693175  0.4633 
# 2        y scale(x1) -0.009965167 0.144736153  0.9451 
# 3       x1        x2 -0.001686185 0.002363374  0.4756 
# 4       x1        x3 -0.001719588 0.002536671  0.4978 

model.list[[1]] = update(model.list[[1]], . ~ x1 + x2 + (1|random))

sem.coefs(model.list, data)

# response predictor      estimate   std.error p.value 
# 1        y        x2 -0.0034419715 0.004703102  0.4643 
# 2        y        x1 -0.0003349071 0.004876150  0.9452 
# 3       x1        x2 -0.0016861854 0.002363374  0.4756 
# 4       x1        x3 -0.0017195875 0.002536671  0.4978
```

I agree that `x1` should be treated the same regardless of transformations in `sem.plot` though since it ostensibly indicates linkages between, at most, two variables.  I'll look into it.

**Comment by jslefche** [comment]
Ok latest version of `sem.plot` should strip transformations from the output plot! Update from Github and give it a whirl...

**Comment by kdarras** [comment]
Oh, that was awesome, thanks!
