### ISSUE TITLE
sem.fit errors

### ISSUE THREAD

**Issue by huifu367** [jslefche/piecewiseSEM#67]
Hi, I have a question about the errors of sem.fit. here is the code:
Shipley<-Shipley2009
> shipley.modlist1=list(
+   lme(Date~DD+lat,data=Shipley,random=~1|site/tree,na.action=na.omit),
+   lme(Growth~Date+lat,data=Shipley,random=~1|site/tree,na.action=na.omit),
+   lme(Growth~Date+lat+DD,data=Shipley,random=~1|site/tree,na.action=na.omit),
+   lmer(Live~Growth+lat+(1|site)+(1|tree),data=Shipley,na.action=na.omit, 
+        family=binomial(link = "logit")),
+   lmer(Live~Growth+lat+DD+(1|site)+(1|tree),data=Shipley,na.action=na.omit, 
+        family=binomial(link = "logit")),
+   lmer(Live~Growth+DD+Date+(1|site)+(1|tree),data=Shipley,na.action=na.omit, 
+        family=binomial(link = "logit")) 
+ )
Warning messages:
1: In lmer(Live ~ Growth + lat + (1 | site) + (1 | tree), data = Shipley,  :
  calling lmer with 'family' is deprecated; please use glmer() instead
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?
3: In lmer(Live ~ Growth + lat + DD + (1 | site) + (1 | tree), data = Shipley,  :
  calling lmer with 'family' is deprecated; please use glmer() instead
4: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0102342 (tol = 0.001, component 3)
5: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?;Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?
6: In lmer(Live ~ Growth + DD + Date + (1 | site) + (1 | tree), data = Shipley,  :
  calling lmer with 'family' is deprecated; please use glmer() instead
7: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0278698 (tol = 0.001, component 3)
8: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?;Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?
> sem.fit(shipley.modlist1, Shipley)
**Error in formulaList.new[[which(sapply(formulaList.new, function(j) all.vars(formula(j))[1] ==  : 
  no such index at level 2**

Why? How do I deal with this problem?

**Comment by jslefche** [comment]
It appears you have two problems:

(1) You have multiple instances of the same response in the model list. You need to collapse those into a single multiple regression, e.g.

```
shipley.modlist2=list(
  
  lme(Date~DD+lat,data=Shipley,random=~1|site/tree,na.action=na.omit),
  lme(Growth~Date+lat + DD,data=Shipley,random=~1|site/tree,na.action=na.omit),
  lmer(Live~Growth+lat+DD+Date+(1|site)+(1|tree),data=Shipley,na.action=na.omit,
       family=binomial(link = "logit"))
) 
```

(2) The second problem is that the model is saturated, i.e., you have identified all possible relationships. This means there are no missing paths with which to construct tests of directed separation. Therefore you cannot obtain an omnibus statistic using `sem.fit`. 

Happy to field any more questions you might have
