### ISSUE TITLE
testing total direct and indirect effects in piecewise SEM

### ISSUE THREAD

**Issue by dcallen** [jslefche/piecewiseSEM#72]
Hey it would be great if there were a function that calculate the total direct and indirect effects of a given predictor variable, and if those effects were significant or not.

**Comment by jslefche** [comment]
Having talked with Jim Grace this is not as easy as it appears and `lavaan` is cryptic in its documentation. For the moment assume P < 0.05 for each path results  in a "significant" indirect relationship, but going to keep this one on the table

**Comment by klausgcea** [comment]
Can't one use the Sobel test equation to approximate standard errors of indirect effects and then use the z-score to test if the indirect effect is significantly different from zero?

**Comment by jslefche** [comment]
Working on this for 2.0

**Comment by efratde** [comment]
Any updates regarding how to calculate indirect and total effects? As well as their significance?

**Comment by jslefche** [comment]
Hello…nothing yet, sorry. You should be able to multiply the coefficients to get the magnitude of the indirect effect by hand. Now that the DAG is generated using igraph it might be easier to write a function to do this by specifying the endpoints but need to look into it more

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by robboyd** [comment]
@dcallen @jslefche it is super simple to calculate direct and total effects by hand. Assessing their significance is a bit more challenging, but can by achieved via bootstrapping. Here's how I did it for a psem model:

`getCoeff <- function(data, indices) {
  
  d <- data[indices, ]
  
  fit <- psem(lmer(expert_score ~ (1|assessor_ID) + prevalence + range_completeness + niche_completeness + n,
                     data = dat),
                lm(n ~ prevalence + range_completeness, data = dat),
                lm(uncertainty ~ n + niche_completeness + prevalence, data = dat),
                data = d)
  
  summary(fit)$coeff$Std.Estimate
  
}

bMod1 <- boot(data = dat,
              statistic = getCoeff,
              R = 1000)`

Then you can use the function boot.SI to obtain various types of confidence interval

**Comment by paternogbc** [comment]
Mark Murphy developed this very nice package to estimate direct/indirect effects of sem models and test significance level with bootstrap. https://murphymv.github.io/semEff/articles/semEff.html
