### ISSUE TITLE
How can I get the value and also the significant level of mediation (indirect) effects with piecewiseSEM?

### ISSUE THREAD

**Issue by Elton-nj** [jslefche/piecewiseSEM#76]
I love piecewiseSEM very much, however,  my knowledge (experience) is quite limited.
I would like to know, whether I can obtain the value and also significant level (P-value) of mediation effects from a path model using piecewiseSEM.

As far as I know, such function is available in lavaan.

see the example:

## in an experiment, there are two exogenous variables (Fact1, Fact2) and two endogenous variables (Var1, Var2), the interaction term (Int) of Fact1 and Fact2 is also considered

Fact1 = rep(c(0,1), each = 50)
Fact2 = rep(c(0,1), each = 50)
Var1 = 0.5 + 0.2 * Fact1 - 0.4 * Fact2 + rnorm(100, 0, 0.1)
Var2 = 0.4 - 0.6 * Fact1 - 0.2 * Fact2 - 0.8 * Int + 0.5 * Var1 + rnorm(100, 0, 0.1)
Int = Fact1 * Fact2
example <- data.frame(Fact1, Fact2, Var1, Var2, Int)
library(lavaan)

# So I built a lavaan based path model to obtain
# direct effects of exogenous variables: d_F1, d_F2, d_Int
# indirect effects of exogenous variables : ind_F1, ind_F2, ind_Int
# total effects of exogenous variables: tl_F1, tl_F2, tl_Int

lavaan.model <- '
Var1 ~ a * Fact1 + b * Fact2
Var2 ~ c * Fact1 + d * Fact2 + e * Int + f * Var1
Fact1 ~~ 0*Fact2
Fact1 ~~ Int
Fact2 ~~ Int
d_F1 := c
ind_F1 := a * f
tl_F1 := d_F1 + ind_F1
d_F2 := d
ind_F2 := b * f
tl_F2 := d_F2 + ind_F2
d_Int := e
ind_Int := 0
tl_Int := d_Int + ind_Int
'

fit.lavaan.model <- sem(lavaan.model, data = example, fixed.x = F, estimator = "MLM")
summary(fit.lavaan.model)

# despite of some warning messages you may get, lavaan can return the value and the significant level of those factors:

lavaan (0.5-20) converged normally after  90 iterations

  Number of observations                           100

  Estimator                                         ML      Robust
  Minimum Function Test Statistic              943.355  283255560.468
  Degrees of freedom                                 2           2
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  0.000
    for the Satorra-Bentler correction

Parameter Estimates:

  Information                                 Expected
  Standard Errors                           Robust.sem

Regressions:
                   Estimate  Std.Err  Z-value             P(>|z|)
  Var1 ~                                                         
    Fact1      (a)   -0.099    0.022              -4.578    0.000
    Fact2      (b)   -0.099    0.022              -4.578    0.000
  Var2 ~                                                         
    Fact1      (c)   -0.533    0.018             -28.870    0.000
    Fact2      (d)   -0.533    0.018             -28.869    0.000
    Int        (e)   -0.533    0.006             -85.734    0.000
    Var1       (f)    0.463    0.086               5.365    0.000

Covariances:
                   Estimate  Std.Err  Z-value             P(>|z|)
  Fact1 ~~                                                       
    Fact2             0.000                                      
    Int               0.125    0.000 490767546041101.750    0.000
  Fact2 ~~                                                       
    Int               0.125    0.000 335797114854423.000    0.000

Intercepts:
                   Estimate  Std.Err  Z-value             P(>|z|)
    Var1              0.509    0.024              21.204    0.000
    Var2              0.410    0.051               8.067    0.000
    Fact1             0.500    0.050               9.950    0.000
    Fact2             0.500    0.050               9.950    0.000
    Int               0.500    0.050               9.950    0.000

Variances:
                   Estimate  Std.Err  Z-value             P(>|z|)
    Var1              0.012    0.002               6.798    0.000
    Var2              0.009    0.001               7.904    0.000
    Fact1             0.250    0.000 490861716013543.188    0.000
    Fact2             0.250    0.000 335815900127115.312    0.000
    Int               0.125    0.000 389488425808240.000    0.000

Defined Parameters:
                   Estimate  Std.Err  Z-value             P(>|z|)
    d_F1             -0.533    0.018             -28.870    0.000
    ind_F1           -0.046    0.012              -3.856    0.000
    tl_F1            -0.579    0.018             -31.316    0.000
    d_F2             -0.533    0.018             -28.869    0.000
    ind_F2           -0.046    0.012              -3.856    0.000
    tl_F2            -0.579    0.018             -31.315    0.000
    d_Int            -0.533    0.006             -85.734    0.000
    ind_Int           0.000                                      
    tl_Int           -0.533    0.006             -85.734    0.000

**Comment by jslefche** [comment]
Duplicated with #72
