### ISSUE TITLE
Latent Variables: Feature request

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#78]
Here's a piece of code I wish worked to look at latent variables in a piecewise SEM.

```
library(piecewiseSEM)
library(lavaan)
mod <- " ind60 =~ x1 + x2 + x3"
mod2 <- "dem60 =~ y1 + a*y2 + b*y3 + c*y4"

modList <- list( 
           sem(mod, data=PoliticalDemocracy, meanstructure=TRUE)
           sem(mod2, data=PoliticalDemocracy, meanstructure=TRUE),
           lm(dem60 ~ ind60, data=pd),
           lm(y5 ~ dem60 , data=pd)

sem.fit(modList, data=pd)
```

Now, I can do something like

```
mod <- " ind60 =~ x1 + x2 + x3"
fit <- sem(mod, data=PoliticalDemocracy, meanstructure=TRUE)
```

To fit a single factor analysis and get a latent variable. I can even extract factor scores using `lavPredict()`

```
> head(lavPredict(fit))
          ind60
[1,] -0.5261683
[2,]  0.1436527
[3,]  0.7143559
[4,]  1.2399257
[5,]  0.8319080
[6,]  0.2123845
```

This makes me wonder if we can't fold latent variables into the piecewise approach via factor analysis of one or more variables - i.e., perhaps fit a full CFA to derive factors that are then used in later models.

Eh?

Eh?

**Comment by jslefche** [comment]
Implement these in `psem` with new operator class: `%=~%`

**Comment by jebyrnes** [comment]
Oh! How/where/example?

**Comment by jslefche** [comment]
Not worked up yet but exported so ready and waiting. `psem` will have to take that operator, construct the latent variable, and extract the loadings to evaluate the other models. This will be tricky and i may need your help, because `psem` wants to evaluate everything as soon as its input...

**Comment by gsadoti** [comment]
It looks like the ability to incorporate latent variables was added in v. 2.0.2. I also see reference to it in the [psem.R](https://github.com/jslefche/piecewiseSEM/blob/c2b5c308ae7ecaf44db0569d0251cc5093e4d54c/R/psem.R), with some syntax on lines 253-257: 
# New operators for latent, composite variables
# `%~=%`
# `%~+%`

Could someone provide a example (i.e., syntax) of how this is implemented? So far all my attempts have returned "... could not find function "%=~%" ." Many thanks for the continued development of this package!

**Comment by jslefche** [comment]
Hi Giancarlo—those are placeholders. We plan to eventually get around to implementing both latent and composite variables but they are a longer-term goal. At the moment, there is no way to incorporate them into `piecewiseSEM`. Sorry about that, Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

________________________________

**Comment by SMSmart** [comment]
Dear Sirs.
I also left a query about implementing the above operators in the comments page for issue 84. However, it looks as if I can use the approach to deriving a composite from a quadratic exemplified by J.Byrnes code for issue 116? Is the intention that the new operator %~+% somehow makes this job easier. Huge thanks for advice and also for this fantastic package. Simon Smart

**Comment by jslefche** [comment]
Hi Simon…unfortunately that operator is a placeholder and hasn’t yet been implemented. You can however find a worked example of a composite in piecewise here: https://jslefche.github.io/sem_book/composite-variables.html Drop a line if you need any help! Cheers, Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by SMSmart** [comment]
Thanks Jon. You are a star.
Si
________________________________

**Comment by SMSmart** [comment]
Dear Jon.

Many thanks for your pointer to the account below. I have read through and feel I understand and am ready to implement my quadratic in piecewiseSEM, however I have one question if you would be so kind. The very last sentence of section 7.3 is “To obtain the indirect effect then, we multiply these paths plus the standardized loading cover on the composite: −0.437∗3.048∗0.292=−0.389−0.437∗3.048∗0.292=−0.389 .” I can see that the 3.048 is the standardised estimate from the lavaan analysis but my question is what kind of standardisation of cover was implemented to arrive at this number? It seems that it cannot be a Z score nor by range. Is it based on subtracting the mean only from each cover variate without dividing through by? I am not a lavaan user but could not find any info in the various lavaan guides either. I probably missed it.

Huge thanks for your time and help,

Simon

**Comment by jslefche** [comment]
Hi simon,

I believe it’s coefficient scaled by the ratio of SDs obtained from the predicted scores. I would have to double check this…

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by robinloveridge** [comment]
Hello, I'm pretty new to SEM in r. But I'm trying to develop an SEM that combines latent variables and takes account of a nested data structure using random effects, so using lmer or lme functions. 

Q1) Is it still the case that confirmatory factor analysis is NOT available in the piecewiseSEM package?
Q2) Is it possible to specify an lmer model in lavaan? My understanding is that its not possible to do this.

Q3) How would you recommend achieving an SEM with latent variables and nested model structure? Is it possible to pass latent variables calculated in lavaan into piecewiseSEM?

Your advice would be much appreciated. Thanks!

**Comment by andrew0302** [comment]
Hey I've got a similar situation as robinloveridge. Can you now estimate latent variables in psem()?

**Comment by jebyrnes** [comment]
So - looks like Bill Shipley has just published a methodology on how to do this - https://www.tandfonline.com/doi/abs/10.1080/10705511.2020.1871355 -  I cannot yet get access to it. Perhaps if we could come up with a simple reproducible example from it, this would let us make some serious progress.

**Comment by andrew0302** [comment]
Does anyone want to collectively email him and ask? I'd be happy to draft the email if I had everyone's addresses, if it makes sense

**Comment by rbfontana** [comment]
Hello, 
Does anyone know if it's possible to use latent variables in piecewiseSEM? If there's a way to use that, how it's the syntax? Or can I use the latent as composite variables?

**Comment by andrew0302** [comment]
See comments just above yours. It's apparently not formally part of the package yet, but has been discussed in the paper linked above. I suggested a collective email to the author(s) where we ask if they have any materials for us to work with.

**Comment by jslefche** [comment]
closing this in advance of new work by shipley and douma

**Comment by morrowcj** [comment]
> closing this in advance of new work by shipley and douma

Is there any update on implementing latent and composite variables using the `%~=%`
`%~+%` operators? Its been a few years.

**Comment by jebyrnes** [comment]
Not here, but, you CAN do it with Bayesian piecewise SEM. I wrote a tutorial on it at https://jebyrnes.github.io/bayesian_sem/bayesian_sem.html
