### ISSUE TITLE
error in sem.coefs standardised when using a factor as predictor

### ISSUE THREAD

**Issue by jordifpages** [jslefche/piecewiseSEM#79]
Here's a model I'm currently analysing:
```
model_direct_effects <- list(
lm(log(RootBiomass+1) ~ Grazing + pH + Xomatter, data = marsh.ok),
lme(Bulk_Density ~ pH + Grazing + Xomatter + Percent_sand, random = ~1|Site, data = marsh.ok),
glm.nb(total_blocks ~ Grazing + RootBiomass + Bulk_Density + Xomatter + Percent_sand + pH, data = marsh.ok))
```

"Grazing" is a categorical variable with 2 levels. The rest of predictors and response variables are continuous.

I have managed to get the unstandardised coefficients doing:
`sem.coef(model_direct_effects)`

But I can't get the standardised coefficients:
`sem.coefs(model_direct_effects, data = marsh.ok, standardize = "scale")`

Because it gives this error: 
> Error in gsub(col.no, paste0("newdata[, ", col.no, "]"), i) : 
>   invalid 'pattern' argument

Any ideas to overcome this?

PS. I'm new to github, so this might not be the best place to ask this type of questions... if that's the case, could you direct me to the right place? Cheers.

**Comment by jslefche** [comment]
New implementation in 2.0
