### ISSUE TITLE
What happens if only 1 model appears in the model list?

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#86]

**Comment by jebyrnes** [comment]
You mean only one relationship? Then that's the basis set!

**Comment by jslefche** [comment]
Heh sorry typo, meant in the model list. Would be nice to get back standardized coefficients, R2, etc

**Comment by jebyrnes** [comment]
Ah - yeah, you should be able to do all of those things, no? Just not calculate anything for a basis set. Perhaps a "Model is saturated, there is no basis set to evaluate the model" in the summary output?

**Comment by jslefche** [comment]
Yup, fixed so throws a warning and returns only coefficients and ultimately R2 for the individual model
