### ISSUE TITLE
sem.fit with glmmadmb 

### ISSUE THREAD

**Issue by vgagic** [jslefche/piecewiseSEM#97]
Hi, I noticed an error message in sem.fit when using a model list with glmmadmb instead of glmer in the shipley2009 example. The error is:  "unused argument (control = control)". 
Is there a fix for this function or am I doing something wrong?

shipley2009.1=na.omit(shipley2009)
str(shipley2009.1)
shipley2009.1$tree=as.factor(shipley2009.1$tree)
shipley2009.1$site=as.factor(shipley2009.1$site)

shipley2009.modlist1 = list(

  lme(DD~lat, random = ~1|site/tree, na.action = na.omit, 
  data = shipley2009.1),
  
  lme(Date~DD, random = ~1|site/tree, na.action = na.omit, 
  data = shipley2009.1),
  
  lme(Growth~Date, random = ~1|site/tree, na.action = na.omit, 
  data = shipley2009),
  
  glmmadmb(Live~Growth+(1|site)+(1|tree), 
  family="binomial", link = "logit", data = shipley2009.1) 
  
  )

sem.fit(shipley2009.modlist1, shipley2009.1)

**Comment by jslefche** [comment]
If you roll back to the prior commit, does it give the same error? 

https://github.com/jslefche/piecewiseSEM/archive/4c74a86efc47e610bf4ebe9c1d180c8da1b6873f.zip

And then install from source.

**Comment by vgagic** [comment]
To install it I used: 
setwd("path")
install("piecewiseSEM-4c74a86efc47e610bf4ebe9c1d180c8da1b6873f")
(directly from the source didn't work)

I still get the same error. It appears to me that this is due to the "sem.missing.paths" function that uses:

 if (is.null(random.formula) | class(basis.mod) == 
                  "glmmadmb") 
                  update(basis.mod, formula(paste(basis.set[[i]][2], 
                    " ~ ", rhs)), control = control, data = data)

but unlike other functions (lme, glmmPQL etc) glmmadmb doesn't have "control" argument in the model specification (but uses "admb.opts=admbControl()"). This is just an idea, but I might be completely wrong.

**Comment by jslefche** [comment]
Hrm if you can hang tight I will try and integrate `glmmadmb` into the development version (2.0) which might get rid of this issue since it has been rewritten from the ground up.

**Comment by srgriffin108** [comment]
Hi, was this ever resolved? I'm having the same issue with glmmadmb

**Comment by jslefche** [comment]
Hoping to get `glmmadmb` in there this week, moved positions so sorry for the delay

**Comment by scxie2** [comment]
I am writing to see whether glmmadmb is intergrated into version 2.00?

**Comment by jslefche** [comment]
Not yet hopefully by next week

____________________________
Jonathan S. Lefcheck, Ph.D.
Post-doctoral Researcher
Bigelow Laboratory for Ocean Science
Phone: +1 (207) 315-2567 ext. 420
Website: www.jonlefcheck.net

**Comment by srgriffin108** [comment]
Hi, were you ever able to integrate glmmadmb into version 2.00? If not, are you still planning to add it in?
