### ISSUE TITLE
Feature Request - Multinomial Regression

### ISSUE THREAD

**Issue by salkeith** [jslefche/piecewiseSEM#98]
Hello. If I understand it correctly, piecewise SEMs seem to be able to handle combinations of regression models. One of the "links" in a model I am currently working on is between a nominal categorical variable as the dependent, and a numerical variable as the independent, so it would be very useful to have the option to specify a multinomial logistic regression as one of the component models. If this makes sense, I would really appreciate if this could be added as an option to piecewiseSEM and I hope I am posting this in the right place. Thanks!

**Comment by jebyrnes** [comment]
What package and function are you using for MLR?

On Apr 24, 2017, at 5:24 AM, Sally Keith <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello. If I understand it correctly, piecewise SEMs seem to be able to handle combinations of regression models. One of the "links" in a model I am currently working on is between a nominal categorical variable as the dependent, and a numerical variable as the independent, so it would be very useful to have the option to specify a multinomial logistic regression as one of the component models. If this makes sense, I would really appreciate if this could be added as an option to piecewiseSEM and I hope I am posting this in the right place. Thanks!

**Comment by salkeith** [comment]
Hi Jarrett

package: nnet
function: multinom

Thanks very much :)
Sal

**Comment by jslefche** [comment]
Hi Sally, this could be done but I’m not familiar with how these multinomial models are estimated. But it may be as simple as having the model class added to the code. Currently traveling but can look into this soon, unless Jarrett has time now

____________________________
Jonathan S. Lefcheck
Post-doctoral Research Associate
Seagrass Ecology Lab
Virginia Institute of Marine Science
Gloucester Point, VA 23062
+1 (804) 684-7150
www.jonlefcheck.net
